Repository autotest/tp-libvirt, pull requests merged in 2020-06, with the labels that each got.

#2795 Wait for scsi_debug
  libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Labels: depend on

#2821 Memory size will automatically align to 256m on pseries
  libvirt/tests/cfg/libvirt_mem.cfg
Labels: minorfix

#2822 Remove unsupported case for pseries
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#2824 Extend exit timeout for pseries
  libvirt/tests/cfg/daemon/daemon_functional.cfg
Labels: minorfix

#2831 Update check for xive
  libvirt/tests/src/cpu/ppccpucompat.py
Labels: minorfix

#2833 remote_access: Add new case for socket activation mode
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Labels: minorfix

#2837 remote_access: Fix a certificate issue
  libvirt/tests/cfg/remote_access/remote_with_tls.cfg
Labels: minorfix

#2828 Modify NPIV wwnn and wwpn related parameter name to match python file…
  libvirt/tests/cfg/npiv/npiv_snapshot.cfg
  libvirt/tests/cfg/npiv/npiv_virtual_disk.cfg
Labels: minorfix

#2818 Add qemu-guest-agent support for v2v on rhel8
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/src/function_test_esx.py
Labels: depend on

#2764 Fix dumpxml cpu-update for s390x
  libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
Labels: minorfix

#2830 Skip checking memory alignment of currentMemory
  libvirt/tests/src/libvirt_mem.py
Labels: minorfix

#2847 remote_access: cache a ticket for GSSAPI authentication
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
  libvirt/tests/src/remote_access/remote_access.py
Labels: minorfix

#2855 acpi is not supported by pseries
  libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg
Labels: minorfix

#2857 Adjust the hugepages for two guests
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: minorfix

#2839 Fix errors in migrate_options_shared.cfg and sriov_migrate.cfg
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/cfg/migration/sriov_migrate.cfg
Labels: minorfix

#2867 Update to check output of vol-list
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
Labels: minorfix

#2853 Modify expected mode to host-model for ppc test
  libvirt/tests/cfg/cpu/vcpu_misc.cfg
Labels: minorfix

#2846 Remove pv_eoi cases from pseries
  libvirt/tests/cfg/libvirt_qemu_cmdline.cfg
Labels: minorfix

#2856 Remove topology if test does not require
  libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
Labels: minorfix

#2863 Set correct hugepage size for power8 and power9 hosts
  libvirt/tests/src/libvirt_mem.py
Labels: minorfix

#2826 Add a migration test with XBZRLE compression
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: high_case

#2874 Add random source for tcp bind mode
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#2868 Fix no more pci slots issue
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#2865 Fix ceph snapshot readonly issue
  libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Labels: minorfix

#2870 Check vm's existance before removing it
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix

#2894 Only need modify disk ownership when no_sec_relabel and non_sec_type
  libvirt/tests/src/svirt/svirt_start_destroy.py
Labels: minorfix
