Repository autotest/tp-libvirt, pull requests merged in 2020-10, with the labels that each got.

#2888 Add migration test cases about memory balloon device
  libvirt/tests/cfg/migration/migrate_mem.cfg
  libvirt/tests/src/migration/migrate_mem.py
Labels: depend on

#3069 guest_numa: Fix incorrect qemu cmd line
  libvirt/tests/src/numa/guest_numa.py
Labels: minorfix

#2991 migration: Add a case about ovs bridge
  libvirt/tests/cfg/migration/migrate_network.cfg
  libvirt/tests/src/migration/migrate_network.py
Labels: depend on, high_case

#3065 Add 2 save/restore cases
  libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
Labels: depend on, high_case

#3074 Fix snapshot-revert case failures
  libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
Labels: minorfix

#3106 Virsh blkdeviotune:Fix the matrix error of slice test
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
Labels: minorfix

#3105 Fix virsh_boot on s390x
  libvirt/tests/cfg/bios/virsh_boot.cfg
Labels: minorfix

#3051 Add set threshold for disk mirroring node BZ1807741 cases
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
Labels: high_case

#3089 Update test params for blockcopy
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
Labels: minorfix

#3068 Fix disk_bus_virtio.device_disk.default case failure
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#3119 Add the missing configuration for virsh_restore test
  libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
Labels: minorfix

#3130 fix error in device-removal-failed event
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#3128 Fix get filesystem info failure by limiting used-bytes difference
  libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
Labels: minorfix

#3090 Add test case to validate bugzilla bug:1804672
  libvirt/tests/cfg/svirt/dac_vm_per_image_start.cfg
Labels: depend on, high_case
