Repository autotest/tp-libvirt, pull requests merged in 2020-07, with the labels that each got.

#2877 v2v: Fix VMChecker initialization problem when converting to ovirt
  provider/v2v_vmcheck_helper.py
  v2v/tests/cfg/convert_from_file.cfg
  v2v/tests/cfg/convert_vm_to_ovirt.cfg
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/cfg/function_test_xen.cfg
  v2v/tests/cfg/specific_kvm.cfg
  v2v/tests/cfg/v2v_options.cfg
  v2v/tests/src/convert_from_file.py
  v2v/tests/src/convert_vm_to_ovirt.py
  v2v/tests/src/function_test_esx.py
  v2v/tests/src/function_test_xen.py
  v2v/tests/src/specific_kvm.py
Labels: depend on

#2896 Fix error message matching problem when converting a running guest
  v2v/tests/cfg/specific_kvm.cfg
Labels: minorfix

#2893 Check windows qemu-ga before all public checkpoints
  v2v/tests/src/function_test_esx.py
Labels: depend on

#2900 Fix the blockcopy error when target size larger than source
  libvirt/tests/src/backingchain/blockcopy.py
Labels: minorfix

#2902 Skip vcpu_affinity test if the host has less than 8 CPUs
  libvirt/tests/src/cpu/vcpu_affinity.py
Labels: minorfix

#2895 remote_access: Add support for traditional mode
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Labels: depend on, minorfix

#2909 Fix attach disk pci issues on s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#2911 A fix for migration
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#2901 Fix TLS connection setup issue
  libvirt/tests/src/remote_access/remote_access.py
Labels: depend on

#2601 Add cases for pci/pcie devices
  libvirt/tests/cfg/controller/controller_functional.cfg
  libvirt/tests/src/controller/controller_functional.py
Labels: depend on

#2875 Update nwfilter with parameters
  libvirt/tests/cfg/virtual_network/iface_update.cfg
  libvirt/tests/src/virtual_network/iface_update.py
Labels: depend on

#2918 Update for failed to restart rsyslog
  libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Labels: minorfix

#2924 Fix blkdeviotune slice test error
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
Labels: minorfix

#2923 virsh_connect: Fix a connect issue
  libvirt/tests/src/virsh_cmd/virsh_connect.py
Labels: minorfix

#2922 Add new case of managedsave-edit/dumpxml/define command
  libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave_extra.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_extra.py
Labels: high_case

#2862 Add some storage migration cases
  libvirt/tests/cfg/migration/migrate_storage.cfg
  libvirt/tests/src/migration/migrate_storage.py
Labels: critical_case, depend on, high_case

#2936 Add version required for some cases
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#2934 Update travis setting
  .travis.yml
  requirements-travis.txt
Labels: request_2_maintainers

#2753 Add virsh domblkthreshold feature cases
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
Labels: high_case

#2940 Fix typo in virsh_event
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#2913 Modify the function call after the function definition changes
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#2916 Update remote_access that uses utils_libvirtd.Libvirtd()
  libvirt/tests/src/remote_access/remote_access.py
Labels: depend on

#2938 Change the libvirt_version usage from tp-libvirt to avocado-vt
  libvirt/tests/src/bios/boot_integration.py
  libvirt/tests/src/bios/virsh_boot.py
  libvirt/tests/src/bios/virsh_boot_tseg.py
  libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
  libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
  libvirt/tests/src/conf_file/qemu_conf/seccomp_sandbox.py
  libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
  libvirt/tests/src/cpu/max_vcpus.py
  libvirt/tests/src/cpu/vm_features.py
  libvirt/tests/src/daemon/daemon_functional.py
  libvirt/tests/src/graphics/graphics_functional.py
  libvirt/tests/src/guest_kernel_debugging/nmi_test.py
  libvirt/tests/src/migration/migrate_ceph.py
  libvirt/tests/src/migration/migrate_vm.py
  libvirt/tests/src/numa/guest_numa.py
  libvirt/tests/src/nwfilter/nwfilter_edit_uuid.py
  libvirt/tests/src/nwfilter/nwfilter_update_lock.py
  libvirt/tests/src/remote_access/remote_access.py
  libvirt/tests/src/serial/serial_functional.py
  libvirt/tests/src/svirt/dac_per_disk_hotplug.py
Labels: minorfix

#2945 Fix dumpxml default value for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_dumpxml.cfg
Labels: minorfix

#2948 Add a case that checking pnp_wait.exe warning for windows guests
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#2946 v2v: Add new case for remote libvirt connection
  v2v/tests/cfg/v2v_options.cfg
  v2v/tests/src/v2v_options.py
Labels: depend on
