Repository autotest/tp-libvirt, pull requests merged in 2020-12, with the labels that each got.

#3104 Add vfio-ap test cases
  libvirt/tests/cfg/svirt/libvirt_ap_passthrough.cfg
  libvirt/tests/src/svirt/libvirt_ap_passthrough.py
Labels: depend on

#3122 Add case for multiple disks backup
  libvirt/tests/cfg/incremental_backup/incremental_backup_multidisk.cfg
  libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
Labels: depend on

#3150 Update ceph pool or image name as per validation feature
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy_xml.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
  libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
  libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
Labels: minorfix

#3120 Add new cases of nat
  libvirt/tests/cfg/virtual_network/iface_network.cfg
  libvirt/tests/src/virtual_network/iface_network.py
Labels: depend on, high_case

#3182 Update the value of guest's vcpus for ioapic_iommu test
  libvirt/tests/cfg/cpu/max_vcpus.cfg
  libvirt/tests/src/cpu/max_vcpus.py
Labels: minorfix

#3188 [nodedev-dumpxml] Remove kernel-dependent check for dasd
  libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg
Labels: minorfix

#3196 Add more mapping pattern as new libvirt version change the qemu cmd line
  libvirt/tests/cfg/numa/guest_numa.cfg
Labels: critical_case

#3174 Fix keywrap test
  libvirt/tests/cfg/svirt/libvirt_keywrap.cfg
  libvirt/tests/src/svirt/libvirt_keywrap.py
Labels: depend on

#3199 Skip virtual network test before libvirt 6.5
  libvirt/tests/src/virtual_network/iface_network.py
Labels: minorfix

#3204 migration: Delete the secret before creating it
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#3207 Fix digest_md5 authentication issue
  libvirt/tests/src/remote_access/remote_access.py
Labels: minorfix

#3168 Fix error_policy_report case failure
  libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Labels: minorfix

#3183 Add virtio packed test cases in disk and scsi controller
  libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
  libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
Labels: depend on

#3211 Fix define error for pervious start error cases
  libvirt/tests/cfg/libvirt_mem.cfg
  libvirt/tests/src/libvirt_mem.py
Labels: minorfix

#3210 Fix memory qemu cmd mapping pattern for new version
  libvirt/tests/cfg/memory/nvdimm.cfg
Labels: minorfix

#3212 Allow redefine checkpoint without domain XML
  libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
Labels: minorfix

#3219 [diagnose_data] update supported vcpu number
  libvirt/tests/cfg/cpu/diagnose_data.cfg
  libvirt/tests/src/cpu/diagnose_data.py
Labels: minorfix

#3222 Extend the timeout for unprivilaged login
  libvirt/tests/src/virtual_network/iface_unprivileged.py
Labels: minorfix
