Repository autotest/tp-libvirt, pull requests merged in 2020-08, with the labels that each got.

#2967 Fix ovmf secure boot failed issue for block/rbd/gluster disk
  libvirt/tests/src/bios/virsh_boot.py
Labels: minorfix

#2962 add cases for dmi-to-pci-bridge controller
  libvirt/tests/cfg/usb_device.cfg
Labels: minorfix

#2950 set_virtlogd: Add test for restart virtlogd.service
  libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
  libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
Labels: minorfix

#2955 Update migrate_bandwidth cases to support modular daemons
  libvirt/tests/cfg/migration/migrate_bandwidth.cfg
  libvirt/tests/src/migration/migrate_bandwidth.py
Labels: depend on

#2667 Add test cases for incremental backup
  libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
  libvirt/tests/cfg/incremental_backup/incremental_backup_push_mode.cfg
  libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
  libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
Labels: MVP_RPL, critical_case, high_case

#2970 Fix the issue that guest can't login after reboot
  libvirt/tests/cfg/memory/nvdimm.cfg
Labels: minorfix

#2968 Adding nwfilter with parameters
  libvirt/tests/cfg/virtual_network/iface_update.cfg
  libvirt/tests/src/virtual_network/iface_update.py
Labels: minorfix

#2973 Fix transient disks issue
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2980 libvirt_hooks: Wait for a few seconds to get log
  libvirt/tests/src/libvirt_hooks.py
Labels: minorfix

#2858 Attach an overlay image based on chap authorized iscsi
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: depend on

#2977 Fix vtpm default version
  libvirt/tests/cfg/virtual_device/tpm_device.cfg
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix

#2983 Fix incorrect format
  libvirt/tests/cfg/virtual_device/tpm_device.cfg
Labels: minorfix

#2986 Fix binding 'vnet0' already exists issue
  libvirt/tests/src/nwfilter/nwfilter_update_vm_running.py
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: minorfix

#2985 v2v: delete 'ipconfig /renew' operation for windows checking
  provider/v2v_vmcheck_helper.py
Labels: minorfix

#2961 v2v: improve codes and add new -o json cases
  provider/v2v_vmcheck_helper.py
  v2v/tests/cfg/convert_from_file.cfg
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/cfg/specific_kvm.cfg
  v2v/tests/cfg/v2v_options.cfg
  v2v/tests/src/convert_from_file.py
  v2v/tests/src/convert_vm_to_libvirt.py
  v2v/tests/src/convert_vm_to_ovirt.py
  v2v/tests/src/function_test_esx.py
  v2v/tests/src/function_test_xen.py
  v2v/tests/src/specific_kvm.py
Labels: depend on

#2989 Fix dumpxml default value for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_dumpxml.cfg
Labels: minorfix

#2988 Fix console device nodes for s390x
  libvirt/tests/cfg/serial/serial_functional.cfg
Labels: minorfix

#2729 Add tests of update device for cdrom slice test
  libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
Labels: high_case

#2992 Retry scsi_debug unload on tear down
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2919 Add test cases for boot/loadparm
  libvirt/tests/cfg/bios/virsh_boot.cfg
  libvirt/tests/src/bios/virsh_boot.py
Labels: depend on

#2995 Add a migration case about xbzrle comp method and parallel
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: high_case

#2990 Fix new merged no more pci slots issue
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#2942 migration: Add a case for a paused VM postcopy migration
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: high_case

#3000 Update error message for multifd tunnelled_migration
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#2998 Update error message for "virsh nodecpustats --cpu <invalid cpunum>"
  libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
Labels: minorfix

#2981 Add virsh guestinfo cases
  libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
Labels: critical_case

#3002 Update case for virt_xml_validate
  libvirt/tests/src/virt_cmd/virt_xml_validate.py
Labels: minorfix

#2979 Update for libvirt_hooks case
  libvirt/tests/src/libvirt_hooks.py
Labels: minorfix

#2969 Add cases for libvirt_package
  libvirt/tests/cfg/libvirt_package.cfg
  libvirt/tests/src/libvirt_package.py
Labels: customer_bug

#3007 Fix "Property '.loadparm' not found" error in bios
  libvirt/tests/src/bios/virsh_boot.py
Labels: minorfix

#3011 Fix restart libvirtd issue in split daemon mode
  libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
Labels: minorfix

#3013 migration: Update error message for disable_keepalive cases
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#2957 Add cases to cover more checking points
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
Labels: minorfix

#2890 Fix hypervisor_cpu_compare
  libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py
Labels: depend on

#3001 Add case to validate Bug 1857735
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Labels: high_case

#2993 Add network cases of port isolated
  libvirt/tests/cfg/virtual_network/virtual_network_multivms.cfg
  libvirt/tests/src/virtual_network/virtual_network_multivms.py
Labels: depend on, high_case

#2958 Update socket mode for SSH transport if it's not supported
  libvirt/tests/src/migration/migrate_vm.py
Labels: depend on

#3014 Fixup a migration case that kills by signal.SIGINT
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3024 Fix error in remove_key_in_conf
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#2984 Fix incorrect usage
  libvirt/tests/cfg/serial/serial_functional.cfg
  libvirt/tests/src/serial/serial_functional.py
Labels: minorfix

#3025 Fix pool autostart test step
  libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
  libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
Labels: minorfix

#3027 Fix variable missing issue in snapshot_create_as
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
Labels: minorfix

#3009 libvirt_vm:set different page number to power8 and power9
  libvirt/tests/src/libvirt_mem.py
Labels: minorfix

#2885 Add 2 more scenarios about update alias
  libvirt/tests/cfg/virtual_network/iface_update.cfg
  libvirt/tests/src/virtual_network/iface_update.py
Labels: depend on
