Repository autotest/tp-libvirt, pull requests merged in 2020-05, with the labels that each got.

#2736 graphics_functional: Fix ipv6 address compressed issue
  libvirt/tests/src/graphics/graphics_functional.py
Labels: minorfix

#2732 libvirt_hooks: Update network hooks message
  libvirt/tests/src/libvirt_hooks.py
Labels: minorfix

#2748 Blacklist RDMA migration on s390x
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#2737 Add check for cmd exists or not for ovs-vsctl
  libvirt/tests/src/virtual_network/iface_ovs.py
Labels: minorfix

#2692 Fix no more pc slots issue in attach block device
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Labels: minorfix

#2752 Fix IDE controller which is not supported in q35 machine type issues
  libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
  libvirt/tests/cfg/virtual_disks/startup_policy.cfg
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#2739 virtio_transitional_blk: download images via download.get_file
  libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
Labels: minorfix

#2754 Add version check for bs xml creation
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Labels: minorfix

#2722 Fix detach disk test audit check failure
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#2765 Create new guest for v2v case 'migrated_vm'
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#2756 virsh_sendkey: Add check for rsyslog restart
  libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Labels: minorfix

#2721 Fix incorrect error message in virsh_vol_download_upload
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
Labels: minorfix

#2755 update the usb_device cfg file
  libvirt/tests/cfg/usb_device.cfg
Labels: minorfix

#2767 Fix interface hotplug
  libvirt/tests/src/virtual_network/iface_hotplug.py
Labels: minorfix

#2773 Fix detach device with alias failure issues
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
Labels: minorfix

#2663 RPL: Add migration cases about net failover
  libvirt/tests/cfg/migration/sriov_migrate.cfg
  libvirt/tests/src/migration/sriov_migrate.py
Labels: High priority

#2777 Fix index range error
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
Labels: minorfix

#2783 Fix controller key parameter issue
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Labels: minorfix

#2714 Add a case for python-pyvmomi
  v2v/tests/cfg/pyvmomi/query_changed_disk_areas.cfg
  v2v/tests/src/pyvmomi/query_changed_disk_areas.py
Labels: depend on

#2672 Add blockcopy rbd backend cases
  libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Labels: High priority, minorfix

#2786 Fix virsh start error case for recent versions
  libvirt/tests/src/virsh_cmd/domain/virsh_start.py
Labels: minorfix

#2788 virsh_boot: fix console output issue
  libvirt/tests/src/bios/virsh_boot.py
Labels: minorfix

#2768 Update error message in pcibridge.cfg
  libvirt/tests/cfg/controller/pcibridge.cfg
Labels: minorfix

#2766 Fix virsh_attach_detach_interface s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
Labels: minorfix

#2760 Fix restore result no options
  libvirt/tests/cfg/virsh_cmd/domain/virsh_save_image_edit.cfg
Labels: minorfix

#2510 Fix libvirt_hugepage on s390x
  libvirt/tests/cfg/libvirt_hugepage.cfg
Labels: depend on, minorfix

#2759 Use class level timeout for serial login
  libvirt/tests/src/virtual_network/iface_network.py
Labels: minorfix

#2789 Fix issues in virtio_transitional_blk/rng/serial
  libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
Labels: minorfix

#2758 Modify the wwnn number since the changes from IT
  libvirt/tests/cfg/npiv/npiv_image_from_pool.cfg
  libvirt/tests/cfg/npiv/npiv_nodedev_create_destroy.cfg
  libvirt/tests/cfg/npiv/npiv_pool_vol.cfg
  libvirt/tests/cfg/npiv/npiv_snapshot.cfg
  libvirt/tests/cfg/npiv/npiv_virtual_disk.cfg
Labels: minorfix

#2780 Fix attach disk no more pci slots issue
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#2774 Add source esx7.0 and change source of v2v tier2 guests to esx7.0
  v2v/tests/cfg/convert_vm_to_libvirt.cfg
  v2v/tests/cfg/convert_vm_to_ovirt.cfg
Labels: depend on

#2747 Remove spicevmc cases from pseries tests
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
Labels: minorfix

#2781 Set panic_model to 'pseries' for ppc tests
  libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Labels: minorfix

#2761 hpt:skip unsupported case and remove topology
  libvirt/tests/src/papr_hpt.py
Labels: minorfix

#2784 Fix the return code of find func issue
  libvirt/tests/src/libvirt_cputune.py
Labels: minorfix

#2645 Add cases of qcow2 image with native luks encryption
  libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_luks.py
Labels: high_case

#2718 Add testcases for virtiofs filesystem device:
  libvirt/tests/cfg/virtual_device/filesystem_device.cfg
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: depend on, high_case

#2794 Sync up minimal VM xml
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2796 Check libvirtd should not crash during net-update
  libvirt/tests/cfg/virsh_cmd/network/virsh_net_update.cfg
  libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
Labels: minorfix

#2654 Add new case for copy_on_read attach disk
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: high_case

#2787 Add one AHCI disk case
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#2792 Fix nwfilter_vm_start possitive_test new_filter ipset_test
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: minorfix

#2793 Add migration with bandwidth cases
  libvirt/tests/cfg/migration/migrate_bandwidth.cfg
  libvirt/tests/src/migration/migrate_bandwidth.py
Labels: high_case

#2744 Change 1 case of svirt from negative to positive
  libvirt/tests/cfg/svirt/dac_nfs_save_restore.cfg
Labels: minorfix

#2690 Add cases of iface operation with unprivileged user
  libvirt/tests/cfg/virtual_network/iface_unprivileged.cfg
  libvirt/tests/src/virtual_network/iface_unprivileged.py
Labels: high_case

#2785 Fixed the shell cmd failure issue in nvdimm test
  libvirt/tests/src/memory/nvdimm.py
Labels: minorfix

#2805 Fix ceph migrate command typo
  libvirt/tests/src/migration/migrate_ceph.py
Labels: minorfix

#2802 Modify the number of hugepages allocated
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: minorfix

#2815 Allow pseries to configure the amount of numa cells separatedly
  libvirt/tests/cfg/virtual_device/filesystem_device.cfg
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: minorfix

#2806 Remove unsupported case from pseries tests
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#2808 Fix xml error for virsh_migrate
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: minorfix

#2810 Remove unnecessary checking for migration
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#2812 Update type of items in processors' list
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#2813 Reset uri to original value in cleanup_dest_vm()
  libvirt/tests/src/migration/migrate_gluster.py
Labels: minorfix

#2814 Update options for migrate_gluster
  libvirt/tests/src/migration/migrate_gluster.py
Labels: minorfix

#2798 migration: Add 2 maxdowntime related cases
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: high_case

#2716 Add memory bandwidth monitor test case
  libvirt/tests/cfg/libvirt_cputune.cfg
  libvirt/tests/src/libvirt_cputune.py
Labels: depend on

#2816 Add missing postcopy option
  libvirt/tests/src/migration/migrate_bandwidth.py
Labels: minorfix

#2817 Apply an old patch of pseries settings of numa tests
  libvirt/tests/cfg/numa/guest_numa.cfg
Labels: minorfix

#2820 Detach non-exists interface from vm should not crash the libvirtd
  libvirt/tests/src/virtual_network/iface_hotplug.py
Labels: minorfix

#2819 Fix channel detach on s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
Labels: minorfix

#2823 Fix only pattern for two_guests
  libvirt/tests/cfg/virtual_device/filesystem_device.cfg
Labels: minorfix
