Repository autotest/tp-libvirt, pull requests merged in 2020-04, with the labels that each got.

#2630 Fix nbd backend save and restore failures
  libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Labels: minorfix

#2631 Fix io_throttling for migration
  libvirt/tests/src/migration/migrate_vm.py
Labels: depend on

#2624 Fix duplicate scsi controller index error
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2626 Add sleep a few seconds between two continuous detach device operations
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2633 Reduce loop times from 100 to 50
  libvirt/tests/cfg/sriov/sriov.cfg
Labels: minorfix

#2634 Hpt cases should only run on Power8
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#2636 Skip gluster rdma cases in blockpull tests
  libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Labels: minorfix

#2627 Skip gluster rdma cases in blockcommit feature
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Labels: minorfix

#2637 Fix file alreadly exists issue in luks
  libvirt/tests/src/virtual_disks/virtual_disks_luks.py
Labels: minorfix

#2639 Fix blockcommand test
  libvirt/tests/src/backingchain/blockcommand.py
Labels: minorfix

#2642 Fix 'host_device' issue because of enable -blockdev in virsh_boot.cfg
  libvirt/tests/cfg/bios/virsh_boot.cfg
Labels: minorfix

#2640 Fix cdrom device bus type error on q35
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2644 Modify the directory path of network pid
  libvirt/tests/src/virtual_network/iface_network.py
Labels: minorfix

#2591 Delete virtioscsi_disk case in sepcific_kvm job
  v2v/tests/cfg/specific_kvm.cfg
Labels: minorfix

#2646 Fix clean up dirty file under disable auth
  libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_luks.py
Labels: minorfix

#2629 Add cases for blkdeviotune
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
Labels: depend on

#2650 Fix no more available PCI slots issue
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#2652 Fix disk virtio bootorder snapshot issue
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#2657 Fix -blockdev inconsistency
  libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
Labels: minorfix

#2660 Fix the pkg install waiting for openvswitch
  libvirt/tests/src/virtual_network/mtu.py
Labels: minorfix

#2656 Fix virtio_disk_hot_unplug_event_watch case
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#2666 Fix syntax error
  libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
Labels: minorfix

#2662 Fix change media cases failures
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py
Labels: minorfix

#2658 Fix restore permission deny
  libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
Labels: minorfix

#2664 Fix change media matrix pre vm state running failure
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: minorfix

#2647 Modify the default perms of socket file after 5.6.0
  libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
Labels: minorfix

#2668 Fix typo
  libvirt/tests/cfg/virtual_network/iface_bridge.cfg
Labels: minorfix

#2671 Fix domain image backing chain check failure in virsh_blockpull
  libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Labels: minorfix

#2674 Restart libvirtd.socket after starting libvirtd foreground
  libvirt/tests/src/daemon/kill_starting.py
Labels: minorfix

#2665 Fix polkit policy
  libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
Labels: depend on, minorfix

#2107 Add test for vhostuser+dpdk
  libvirt/tests/cfg/virtual_network/iface_options.cfg
  libvirt/tests/src/virtual_network/iface_options.py
Labels: depend on

#2589 Block rhv output for special_name case
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#2685 Update error message for migration with disable keepalive case
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#2682 Fix 'virsh migrate-postcopy' command failure
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#2686 Fix the hot unplug max slots memory device can't find issue
  libvirt/tests/cfg/libvirt_mem.cfg
  libvirt/tests/src/libvirt_mem.py
Labels: minorfix

#2681 Fix serial func not iterable
  libvirt/tests/src/serial/serial_functional.py
Labels: minorfix

#2696 Fix the failure of mcast
  libvirt/tests/src/virtual_network/iface_options.py
Labels: minorfix

#2694 Fix pool destory failure in volume_application
  libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py
Labels: minorfix

#2697 Don't check blockcopy job finishes with minimal bandwidth
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
Labels: minorfix

#2698 Fix no vol in pool issue
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
Labels: minorfix

#2699 Change attach_times to 255 from 256 for the max_slots
  libvirt/tests/cfg/libvirt_mem.cfg
Labels: minorfix

#2700 Fix "Cannot grow device files" error
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
Labels: minorfix

#2609 RFE: Add migration cases about vtpm device
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: depend on

#2709 Fix no pagesize on node
  libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
Labels: minorfix

#2703 Add debug information for multipath
  libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
Labels: minorfix

#2695 Fix insuffient mem pages
  libvirt/tests/cfg/numa/guest_numa.cfg
  libvirt/tests/src/numa/guest_numa.py
Labels: depend on, minorfix

#2688 Fix minor issue
  libvirt/tests/cfg/migration/migrate_vm.cfg
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#2333 migration: adopt utils_test.libvirt to migration
  libvirt/tests/src/migration/migrate_ceph.py
  libvirt/tests/src/migration/migrate_gluster.py
  libvirt/tests/src/migration/migrate_options_shared.py
  libvirt/tests/src/migration/migrate_vm.py
  libvirt/tests/src/migration/migrate_with_legacy_guest.py
  libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_compcache.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_vm_cfg.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
  libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
Labels: minorfix

#2720 Fix virsh detach device alias failures
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
Labels: minorfix

#2717 Fix Failed to kill libvirtd issue
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: minorfix

#2719 Fix nwfilter vm start case failure
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: minorfix

#2543 tpm_dev: vtpm auto
  libvirt/tests/cfg/virtual_device/tpm_device.cfg
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: depend on

#2728 Update usage of contr create func
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
  libvirt/tests/src/virtio_transitional/virtio_transitional_vsock.py
Labels: depend on, minorfix
