Repository autotest/tp-libvirt, pull requests merged in 2020-09, with the labels that each got.

#3033 Add config file with split daemon for host_uuid cases
  libvirt/tests/src/conf_file/libvirtd_conf/host_uuid.py
Labels: minorfix

#3026 migrate_vm: Add test matrix for normal live_migration with ssh/tcp/tls
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#3037 nmi_test: extend timeout value
  libvirt/tests/src/guest_kernel_debugging/nmi_test.py
Labels: minorfix

#3019 Add pidfile for split daemon mode
  libvirt/tests/src/daemon/kill_started.py
Labels: minorfix

#2889 Fix hypervisor-cpu-compare on s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py
Labels: depend on

#3043 Fix the no pci slot issue
  libvirt/tests/cfg/nwfilter/nwfilter_binding_list.cfg
  libvirt/tests/src/nwfilter/nwfilter_binding_list.py
Labels: minorfix

#3041 Fix the clean-traffic nwfilter missing issue
  libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg
Labels: minorfix

#3040 Fix the attach interface issue
  libvirt/tests/cfg/nwfilter/nwfilter_binding_dumpxml.cfg
Labels: minorfix

#3039 virsh_event: Extend timeout value
  libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#3022 Update func invoke usage
  libvirt/tests/src/migration/migrate_options_shared.py
  libvirt/tests/src/migration/migrate_vm.py
  libvirt/tests/src/migration/sriov_migrate.py
Labels: depend on

#3042 v2v: Add a new case about reducing v2v log size
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/src/function_test_esx.py
  v2v/tests/src/v2v_options.py
Labels: depend on

#3017 Fix a problem to check network connectivity correctly after migaration
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: minorfix

#3052 auto_dump: Move debug information
  libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
Labels: minorfix

#3056 Correct version of eoi support to 6.0.0
  libvirt/tests/src/libvirt_qemu_cmdline.py
Labels: minorfix

#3031 v2v: Add some new cases(luks, '-ip')
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/src/function_test_esx.py
Labels: depend on

#3057 Update usage of cpu.numa_cell
  libvirt/tests/src/controller/controller_functional.py
  libvirt/tests/src/controller/multiple_controller_ppc.py
  libvirt/tests/src/libvirt_mem.py
  libvirt/tests/src/memory/memory_discard.py
  libvirt/tests/src/memory/nvdimm.py
  libvirt/tests/src/numa/guest_numa.py
  libvirt/tests/src/papr_hpt.py
  libvirt/tests/src/sriov/sriov.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
  libvirt/tests/src/virtual_network/iface_options.py
Labels: depend on

#3021 virsh_migrate_copy_storage: update invoking a function
  libvirt/tests/src/migration/migrate_options_shared.py
  libvirt/tests/src/migration/migrate_vm.py
  libvirt/tests/src/migration/sriov_migrate.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
Labels: depend on

#3054 Fix a firewall-cmd error
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#2964 Fix controller target
  libvirt/tests/src/controller/controller_functional.py
Labels: depend on, minorfix

#2841 Add integration test cases for backup and backing chain
  libvirt/tests/cfg/incremental_backup/incremental_backup_backing_chain.cfg
  libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
Labels: MVP_RPL

#3061 v2v: delete case function_test_xen..encryped
  v2v/tests/cfg/function_test_xen.cfg
Labels: minorfix

#2963 Add cases for pcie hotlug option
  libvirt/tests/cfg/controller/pcie_controllers.cfg
  libvirt/tests/src/controller/pcie_controllers.py
Labels: MVP_RPL, critical_case, depend on

#3062 Fix the nwfilter test cases as the feature changes
  libvirt/tests/cfg/nwfilter/filter_aready_present_binding.cfg
  libvirt/tests/cfg/nwfilter/nwfilter_binding_delete.cfg
  libvirt/tests/src/nwfilter/nwfilter_binding_delete.py
  libvirt/tests/src/nwfilter/nwfilter_binding_dumpxml.py
  libvirt/tests/src/nwfilter/nwfilter_binding_list.py
Labels: minorfix

#3064 Update the expected result as libvirt feature changes
  libvirt/tests/src/virtual_network/iface_options.py
Labels: minorfix

#3063 v2v: remove qemu-guest-agent version checking in VM
  v2v/tests/src/function_test_esx.py
Labels: minorfix

#3067 Fix virsh update device failures cases
  libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
Labels: minorfix

#3066 Update nvdimm hotplug case to support pseries
  libvirt/tests/cfg/memory/nvdimm.cfg
  libvirt/tests/src/memory/nvdimm.py
Labels: minorfix

#3060 Fix xml error when setting numa_cell to vmcpuxml
  libvirt/tests/src/controller/multiple_controller_ppc.py
Labels: minorfix

#3035 Fix remote_mode issue that is not supported for SSH
  libvirt/tests/src/migration/migrate_bandwidth.py
  libvirt/tests/src/migration/migrate_gluster.py
  libvirt/tests/src/migration/migrate_options_shared.py
  libvirt/tests/src/migration/migrate_storage.py
  libvirt/tests/src/migration/migrate_with_legacy_guest.py
  libvirt/tests/src/migration/sriov_migrate.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: depend on

#3058 Correct dd_data_to_vm usage
  libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
  libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
  libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
Labels: depend on

#3083 Virsh_update_device:Fix slice test with sharable error
  libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
Labels: minorfix

#3084 Fix vtpm on ppc
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#3072 Fix an issue that VM's IP address can't be obtained after migration
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3088 Update error message for max_vcpus.negative_test.ioapic_iommu
  libvirt/tests/cfg/cpu/max_vcpus.cfg
  libvirt/tests/src/cpu/max_vcpus.py
Labels: minorfix

#3081 virsh_migrate: Fix unsupported direct socket mode issue
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: minorfix

#3093 Fix the problems in check_vm_disk_after_migration
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3092 Fix wrong format of setting params for specific machine type
  libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
Labels: minorfix

#3097 virsh_migrate: Don't ignore status of virsh define
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: minorfix

#3096 Fix direct mode issue for virsh_migrate_copy_storage
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
Labels: minorfix

#3094 Correct the usages of VMManager.check_network
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: minorfix

#2873 Add vlan tag into the interface xml
  libvirt/tests/cfg/sriov/sriov.cfg
  libvirt/tests/src/sriov/sriov.py
Labels: depend on

#3079 Add a case of managedsave-remove
  libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Labels: high_case

#3101 virtual_disks_multidisks: Remove volume_lun cases
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#3102 virtual_disks_multidisks: rm the cases of usb bus together with devic…
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix
