Repository autotest/tp-libvirt, pull requests merged in 2020-11, with the labels that each got.

#3136 Update ceph_disk_name to EXAMPLE_DISK_NAME
  libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_auth.cfg
Labels: minorfix

#3078 Add new case for nfv performance check
  libvirt/tests/cfg/virtual_network/iface_options.cfg
  libvirt/tests/src/virtual_network/iface_options.py
Labels: high_case

#3071 controller_functional: Fix wrong bus number
  libvirt/tests/cfg/controller/controller_functional.cfg
  libvirt/tests/src/controller/controller_functional.py
Labels: depend on, minorfix

#3149 pcie_controllers: support auto index
  libvirt/tests/cfg/controller/pcie_controllers.cfg
  libvirt/tests/src/controller/pcie_controllers.py
Labels: depend on

#3075 Add new cases for mixed detach disk
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
Labels: customer_bug

#3141 Filter out hypervisor-cpu-compare on s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
Labels: minorfix

#3142 Fix hypervisor-cpu-compare for host-processor on s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
Labels: minorfix

#3073 migrate_vm: Update to set migration speed
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#3153 Fix for "IndexError: list index out of range"
  libvirt/tests/src/numa/guest_numa.py
Labels: minorfix

#2999 Add migration test with rng device
  libvirt/tests/cfg/migration/migrate_with_virtual_devices.cfg
  libvirt/tests/src/migration/migrate_with_virtual_devices.py
Labels: depend on

#3140 Add cases for pull mode backup with tls enabled
  libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
  libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Labels: depend on, high_case

#3152 pcie_controllers: new case for multiplug
  libvirt/tests/cfg/controller/pcie_controllers.cfg
  libvirt/tests/src/controller/pcie_controllers.py
Labels: high_case

#3134 Add client private key encryption cases on nbd
  libvirt/tests/cfg/virtual_disks/virtual_disks_nbd.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Labels: depend on, high_case

#3085 Add test cases for keywrap support on s390x
  libvirt/tests/cfg/svirt/libvirt_keywrap.cfg
  libvirt/tests/src/svirt/libvirt_keywrap.py
Labels: critical_case, depend on

#3154 Fix the failure for nvdimm memory case as the qemu cmd line changed in the new version
  libvirt/tests/cfg/memory/nvdimm.cfg
Labels: minorfix

#3163 Use new way to prepare nbd configs for full backup data download
  libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
Labels: minorfix

#3164 Fix the 'clean-traffic' nwfilter missing issue
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: minorfix

#3117 migrate_vm: Remove steps of setting selinux mode to permissive
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3161 auto_dump: replace process.kill with process.terminate
  libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
Labels: minorfix

#3170 v2v: fix boottype checking issue on rhv4.4
  provider/v2v_vmcheck_helper.py
Labels: depend on

#3173 Update incorrect param
  libvirt/tests/cfg/virt_cmd/virt_xml_validate.cfg
Labels: minorfix

#3144 [Batch 1] Fix Admin API cases for split daemon mode
  libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_clients_info.cfg
  libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_list.cfg
  libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_threadpool_info.cfg
  libvirt/tests/src/virt_admin/monitor/virt_admin_srv_clients_info.py
  libvirt/tests/src/virt_admin/monitor/virt_admin_srv_list.py
  libvirt/tests/src/virt_admin/monitor/virt_admin_srv_threadpool_info.py
Labels: depend on

#3175 Fix test.cancel was not thrown
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix
