Repository autotest/tp-libvirt, pull requests merged in 2021-02, with the labels that each got.

#3295 Fix the case with qxl secondary video device with packed virtqueues
  libvirt/tests/src/virtual_device/video_devices.py
Labels: minorfix

#3264 Dynamic Numa nodes usage added into freepages function
  libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
Labels: minorfix

#3269 kill_started: wait a little longer for SIGABRT and SIGSEGV
  libvirt/tests/cfg/daemon/kill_started.cfg
  libvirt/tests/src/daemon/kill_started.py
Labels: minorfix

#3265 Add one more scenario about network autostart
  libvirt/tests/cfg/virsh_cmd/network/virsh_net_autostart.cfg
  libvirt/tests/src/virsh_cmd/network/virsh_net_autostart.py
Labels: minorfix

#3271 Add memory stats for virtio-{non}-transitional memballoon
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
  libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py
Labels: minorfix

#3259 Add clone and resize volume cases for qcow2 encryption volume
  libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg
  libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
Labels: minorfix

#3223 Update bridge type interface with network type xml
  libvirt/tests/cfg/virtual_network/iface_bridge.cfg
  libvirt/tests/src/virtual_network/iface_bridge.py
Labels: minorfix

#3301 Fix "insufficient free space" in logical pool
  libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create_from.cfg
Labels: minorfix

#3300 Use enable_inc_backup_for_vm method to make code clean
  libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
  libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
  libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
  libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
  libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
Labels: minorfix

#3302 v2v: clean vms variant for v2v_options job
  v2v/tests/cfg/v2v_options.cfg
Labels: minorfix

#3247 nvdimm:check minimum target size when defining vm
  libvirt/tests/cfg/memory/nvdimm.cfg
  libvirt/tests/src/memory/nvdimm.py
Labels: minorfix

#3304 Remove tests of input devices with ps2 bus from pseries tests
  libvirt/tests/cfg/virtual_device/input_devices.cfg
Labels: minorfix

#3313 virsh_snapshot_disk: use log not cancel
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Labels: minorfix

#3317 Fix the virsh event issues
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#3286 Add 1 case of vm features: kvm poll-control
  libvirt/tests/cfg/cpu/vm_features.cfg
  libvirt/tests/src/cpu/vm_features.py
Labels: depend on

#3244 Enable transient disk feature on file based backend
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: MVP_RPL

#3318 Fix the issue in the final clean up steps
  libvirt/tests/src/virtual_network/iface_bridge.py
Labels: minorfix

#3319 Add libvirt version check when apply slice attribute for luks encrypt…
  libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
Labels: minorfix

#3323 Set multiple_controller_ppc tests to only run on pseries
  libvirt/tests/cfg/controller/multiple_controller_ppc.cfg
Labels: minorfix

#3320 Skip the negative lease related case on unsupported version
  libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Labels: minorfix

#3325 Add libvirt version checking for scsi packed feature case
  libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
Labels: minorfix

#3324 Remove code for temporary workaround for bz 1658988
  libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
Labels: minorfix

#3256 Add some cases to check migration over unix socket
  libvirt/tests/cfg/migration/migrate_over_unix.cfg
  libvirt/tests/src/migration/migrate_over_unix.py
Labels: critical_case, depend on, high_case
