Repository autotest/tp-libvirt, pull requests merged in 2021-06, with the labels that each got.

#3516 Increase memory size to fix vm crash some time
  libvirt/tests/cfg/memory/memory_discard.cfg
Labels: minorfix

#3512 migration: No result check for some migration cases
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#3400 Add case for vcpupin/emulatorpin/iothreadpin
  libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin_mix.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin_mix.py
Labels: depend on

#3476 Add vhostuser disk cases
  libvirt/tests/cfg/virtual_disks/virtual_disks_vhostuser.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py
Labels: depend on

#3488 virsh_set_get_user_sshkeys: Add cases for set/get-user-sshkeys commands
  libvirt/tests/cfg/virsh_cmd/domain/virsh_set_get_user_sshkeys.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_set_get_user_sshkeys.py
Labels: critical_case, depend on

#3447 Add the check for noqueue tun device
  libvirt/tests/cfg/virtual_network/iface_network.cfg
  libvirt/tests/src/virtual_network/iface_network.py
Labels: depend on

#3527 One name fix
  libvirt/tests/src/virtual_network/iface_options.py
Labels: minorfix

#3523 Disable verify_host_dmesg in nwfilter_vm_start.cfg to avoid bringing …
  libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg
Labels: minorfix

#3532 live_migration: Fix remote qemu conf restore issue
  libvirt/tests/src/migration/live_migration.py
Labels: minorfix

#3537 v2v: always install virt-v2v package when recovering envrionment
  v2v/tests/src/v2v_options.py
Labels: minorfix

#3497 sriov_migration: Add 3 cases
  libvirt/tests/cfg/migration/sriov_migrate.cfg
  libvirt/tests/src/migration/sriov_migrate.py
Labels: depend on, high_case

#3536 virsh_boot: Update error message
  libvirt/tests/cfg/bios/virsh_boot.cfg
Labels: minorfix

#3534 [filesystem_device][virtio-fs] Add version switch
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: minorfix

#3490 SRIOV: Add 3 net failover cases
  libvirt/tests/cfg/sriov/sriov_net_failover.cfg
  libvirt/tests/src/sriov/sriov_net_failover.py
Labels: high_case

#3505 Do cgroup2 compatible fix for memtune test
  libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py
Labels: depend on

#3546 v2v: delete all windows configuration from xen
  v2v/tests/cfg/function_test_xen.cfg
Labels: minorfix

#3548 Fix the format error
  libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Labels: minorfix

#3549 Fix function name error
  libvirt/tests/src/virtual_network/iface_bridge.py
Labels: minorfix

#3551 Delete one invalid case for update device
  libvirt/tests/cfg/virtual_network/iface_update.cfg
Labels: minorfix

#3513 Add debug logs to virsh.blockcopy tests
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
Labels: minorfix

#3524 remote_access: new tests added for uri aliases/default
  libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
  libvirt/tests/src/remote_access/remote_access.py
Labels: depend on

#3554 vcpu_cache: Update the error message
  libvirt/tests/cfg/cpu/vcpu_cache.cfg
Labels: minorfix

#3552 virtio_transitional_blk_negative：Correct the exception
  libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py
Labels: minorfix

#3535 Add a migration case to check the VM with direct type interface
  libvirt/tests/cfg/migration/migrate_network.cfg
  libvirt/tests/src/migration/migrate_network.py
Labels: customer_bug

#3425 remote_access: New case for SSH with SASL plain
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
  libvirt/tests/src/remote_access/remote_access.py
Labels: depend on

#3562 Increase current memory size
  libvirt/tests/cfg/memory/memory_discard.cfg
Labels: minorfix

#3545 Correct compare_qemu_version
  libvirt/tests/src/migration/migrate_with_virtual_devices.py
Labels: minorfix

#3547 migration: Update the error message for negative multifd cases
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#3559 iothread: Update the value of iothread_quota
  libvirt/tests/src/cpu/iothread.py
Labels: minorfix

#3517 Add cases for tls verify client migration
  libvirt/tests/cfg/migration/live_migration.cfg
  libvirt/tests/src/migration/live_migration.py
  provider/migration/migration_base.py
Labels: depend on, high_case

#3531 Add precheck whether nwfilter exists before call create create_nwfilt…
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: depend on

#3591 migrate_vm: Fix local variable 'xml_path' referenced before assignment
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3597 Fix libvirt_hostdev sgio related cases failure
  libvirt/tests/src/libvirt_scsi_hostdev.py
Labels: minorfix

#3592 v2v: don't test to rhv when VIRITO_WIN or virtio-win is not set
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix
