Repository autotest/tp-libvirt, pull requests merged in 2021-05, with the labels that each got.

#3371 Add memory hotplug test case
  libvirt/tests/cfg/memory/memory_hotplug.cfg
  libvirt/tests/src/memory/memory_hotplug.py
Labels: depend on

#3391 Add wait for writing file success before return
  libvirt/tests/src/virtual_network/mtu.py
Labels: depend on

#3487 Disable qemu-cmd-check for libvirt_mem basic test
  libvirt/tests/cfg/libvirt_mem.cfg
Labels: minorfix

#3491 Fix the tpm failure on /tmp dir
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix

#3441 virsh_guestinfo: Added the the case of virsh guestinfo
  libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
Labels: critical_case

#3432 Fix blkiotune cgroup2 issues
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blkiotune.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
Labels: depend on

#3454 Add one case about test multiqueue on direct type interface
  libvirt/tests/cfg/virtual_network/iface_options.cfg
  libvirt/tests/src/virtual_network/iface_options.py
Labels: depend on

#3433 Add wait_for_event for change-media operation
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: depend on

#3503 virsh_blockpull: Update to use data_dir
  libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Labels: minorfix

#3502 virsh_blockcommit: Update to use data_dir
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Labels: minorfix

#3494 v2v: set an initial setting for luks password
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#3384 Add blockcommit relative path cases
  libvirt/tests/cfg/virtual_disks/virtual_disks_relative_blockcommit.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_relative_blockcommit.py
Labels: depend on

#3481 add case for cancel migration
  libvirt/tests/cfg/migration/live_migration.cfg
  libvirt/tests/src/migration/live_migration.py
  provider/migration/migration_base.py
Labels: depend on

#3520 virsh_blockcopy.py: move get_tmp_dir() to get_data_dir()
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
Labels: minorfix

#3519 Fix virsh_attach_detach_interface aarch64
  libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
Labels: minorfix

#3522 Fix port checking ignored
  libvirt/tests/src/migration/live_migration.py
Labels: minorfix
