Repository autotest/tp-libvirt, pull requests merged in 2021-01, with the labels that each got.

#3231 migrate_vm: Cold plug two pcie-root-port controllers for q35 vm
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3232 virsh_migrate: Cold plug pcie-to-pci-bridge controller for q35 vm
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Labels: minorfix

#3228 pcie_controllers:fix incorrect quote
  libvirt/tests/cfg/controller/pcie_controllers.cfg
Labels: minorfix

#3226 Fix numa issue in guest_numa.cfg
  libvirt/tests/cfg/numa/guest_numa.cfg
Labels: minorfix

#3225 Support --source-initiator option in iscsi-direct pool
  libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
  libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
Labels: minorfix

#3224 papr_hpt:use new func 'get_family()' provided by avocado:82
  libvirt/tests/src/papr_hpt.py
Labels: minorfix

#3217 v2v: add a new positive --mac static ip case
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/src/function_test_esx.py
Labels: depend on

#3146 Add memory HMAT related test cases
  libvirt/tests/cfg/memory/hmat.cfg
  libvirt/tests/src/memory/hmat.py
Labels: depend on, high_case

#3238 Add --nvram option for undefine
  libvirt/tests/src/virsh_cmd/domain/virsh_create.py
Labels: minorfix

#3235 Extend the internal timeout for serial_login
  libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
Labels: minorfix

#3234 migrate_vm: Replace nbd-server-add with block-export-add
  libvirt/tests/cfg/migration/migrate_vm.cfg
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3237 Check whether pkg is successfully installed
  libvirt/tests/src/memory/nvdimm.py
Labels: minorfix

#3240 Fix domblkthreshold mirror mode blockcommit cases
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
Labels: minorfix

#3243 Fix errors of virsh_event tests
  libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#3202 Add testcases for embedded qemu driver
  libvirt/tests/cfg/embedded_qemu/embedded_qemu.cfg
  libvirt/tests/src/embedded_qemu/embedded_qemu.py
Labels: depend on

#3248 [detach_device][cdrom] fix test for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
Labels: minorfix

#3251 Fix for matching failure as '' added in output around vm name
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix

#3254 Fix mapping pattern again for numa as some PR revert it
  libvirt/tests/cfg/numa/guest_numa.cfg
Labels: critical_case, minorfix

#3258 vcpu_feature:Remove case unsupported by pseries
  libvirt/tests/cfg/cpu/vcpu_feature.cfg
Labels: minorfix

#3221 Set controller for ppc test to support hotplug/unplug
  libvirt/tests/src/svirt/svirt_attach_disk.py
Labels: minorfix

#3245 libvirt_mem:replace function get_cpu_arch with get_family
  libvirt/tests/src/libvirt_mem.py
Labels: minorfix

#3181 Add a case to migrate VM with direct type interface
  libvirt/tests/cfg/migration/migrate_network.cfg
  libvirt/tests/src/migration/migrate_network.py
Labels: depend on, high_case

#3266 v2v: add a new rhv disk checkpoint for bz#1616226
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#3220 Check the libvirtd log when rename the veth interface
  libvirt/tests/cfg/virtual_network/iface_rename.cfg
  libvirt/tests/src/virtual_network/iface_rename.py
Labels: customer_bug

#3277 Virtual disks multidisks: fix IDE issues on aarch64
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#3272 Fix local variable 'vm' referenced before assignment
  libvirt/tests/src/memory/hmat.py
Labels: minorfix

#3257 Add blockcopy shallow option case
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
Labels: minorfix
