Repository autotest/tp-libvirt, pull requests merged in 2021-04, with the labels that each got.

#3373 [libvirt_ap_passthrough] Unload module at teardown
  libvirt/tests/src/svirt/libvirt_ap_passthrough.py
Labels: depend on, minorfix

#3379 Add case of update iface link
  libvirt/tests/src/virtual_network/iface_update.py
Labels: depend on

#3419 Fix usb disk error_test4 failure by adding define_error = yes
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Labels: minorfix

#3420 migration: Fix dhclient command not found problem
  libvirt/tests/src/migration/migrate_network.py
Labels: minorfix

#3421 vcpu_cache: Fix a regex problem
  libvirt/tests/cfg/cpu/vcpu_cache.cfg
Labels: minorfix

#3413 update cpu xml with host-model
  libvirt/tests/src/libvirt_mem.py
  libvirt/tests/src/numa/guest_numa.py
Labels: minorfix

#3215 Added some cases of guest agent
  libvirt/tests/cfg/guest_agent.cfg
  libvirt/tests/src/guest_agent.py
Labels: depend on

#3435 [virsh_blockjob] Introduce configuration to slow down blockjob
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockjob.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py
Labels: minorfix

#3437 Cgroup V2: Update virsh_schedinfo cases
  libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
Labels: depend on

#3443 nwfilter_vm_start: params value update for modify_vm_iface()
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: depend on, minorfix

#3402 Add testcase for vnc port 5900
  libvirt/tests/cfg/graphics/graphics_functional.cfg
Labels: minorfix

#3417 virsh_detach_device_alias: Fix tmp file removed
  libvirt/tests/src/ppc_device.py
  libvirt/tests/src/sriov/sriov.py
  libvirt/tests/src/vfio.py
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Labels: depend on

#3350 Add cases to cover disk metadata_cache feature
  libvirt/tests/cfg/virtual_disks/virtual_disks_metadatacache.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_metadatacache.py
Labels: depend on, high_case

#3438 Add new case of attaching iface with coalesce
  libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
Labels: depend on

#3423 controller_functional: fix host-model missing
  libvirt/tests/src/controller/controller_functional.py
Labels: depend on

#3439 Add 2 new cases for "get vhost-user VNIC stats by domstats" and "vhostuser with dpdk"
  libvirt/tests/cfg/virtual_network/iface_options.cfg
  libvirt/tests/src/virtual_network/iface_options.py
Labels: depend on, high_case

#3403 virsh_attach_detach_disk: Fix "No more PCI slots" error
  libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: depend on

#3449 Fix attach_detach disk by switching get_tmp_dir to get_data_dir
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#3430 Add new case of update interface with coalesce
  libvirt/tests/cfg/virtual_network/iface_update.cfg
  libvirt/tests/src/virtual_network/iface_update.py
Labels: depend on

#3459 remote_access:Fix remote unix readonly sasl
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Labels: minorfix

#3462 Add p2p migration case for with_migrate_disks
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#3431 migration: Add some live migration cases
  libvirt/tests/cfg/migration/live_migration.cfg
  libvirt/tests/src/migration/live_migration.py
Labels: critical_case, depend on, high_case

#3455 virsh_snapshot_create_as: replace /tmp with new dir
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Labels: depend on
