Repository autotest/tp-libvirt, pull requests merged in 2021-09, with the labels that each got.

#3747 Fix local variable 'virsh_session' referenced before assignment
  provider/migration/migration_base.py
Labels: minorfix

#3602 vcpu_nested: add case for cpu change
  libvirt/tests/cfg/cpu/vcpu_nested.cfg
  libvirt/tests/src/cpu/vcpu_nested.py
Labels: depend on

#3754 sriov: Add timeout to recover_vf
  provider/sriov/sriov_base.py
Labels: minorfix

#3674 Add 3 cases for virtual network about dnsmasq
  libvirt/tests/cfg/virtual_network/iface_network.cfg
  libvirt/tests/src/virtual_network/iface_network.py
Labels: depend on

#3636 virtual_disks_rotation_rate: Add case for disk rotation
  libvirt/tests/cfg/virtual_disks/virtual_disks_rotation_rate.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_rotation_rate.py
Labels: depend on

#3652 virsh_vcpupin: Add case for vcpupin
  libvirt/tests/cfg/cpu/vcpupin.cfg
  libvirt/tests/src/cpu/vcpupin.py
Labels: depend on

#3723 Add test case to cover set block threshold with with dev
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
Labels: high_case

#3782 Update the test.fail() to test.cancel()
  libvirt/tests/src/virtual_network/iface_rename.py
Labels: minorfix

#3767 Fix nbd default port pre-occupied issue
  libvirt/tests/cfg/virtual_disks/virtual_disks_nbd.cfg
Labels: minorfix

#3786 sriov: Fix a command failure
  provider/sriov/sriov_base.py
Labels: minorfix

#3785 [minor fix] virsh_deprecate_api: Raise cancel and fail exceptions
  libvirt/tests/src/virsh_cmd/host/virsh_deprecate_api.py
Labels: minorfix

#3713 virsh_cpu_xml: add cases for cpu
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
  libvirt/tests/deps/cap_mix.xml
  libvirt/tests/deps/capabilities.xml
  libvirt/tests/deps/capability_cpu.xml
  libvirt/tests/deps/cpu.xml
  libvirt/tests/deps/domcapabilities.xml
  libvirt/tests/src/virsh_cmd/domain/virsh_cpu_xml.py
Labels: depend on

#3799 [minor fix] memory_misc: Fix 'member_descriptor' object has no attribute 'getroot'
  libvirt/tests/src/memory/memory_misc.py
Labels: minorfix

#3763 Fix multi_disks_test disks boot nfs pool failure
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#3798 Fix virsh.change_media_matrix..default.eject_update case failure
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: minorfix

#3790 timer_management: Update old usage of VMCLOCKXML
  libvirt/tests/src/timer_management.py
Labels: depend on

#3805 Update one parameter name of func detach_device()
  libvirt/tests/src/sriov/sriov_managed.py
  libvirt/tests/src/sriov/sriov_net_failover.py
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
  libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
  libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
  libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
  libvirt/tests/src/virtual_disks/virtual_disks_metadatacache.py
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
  libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
  libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
  libvirt/tests/src/virtual_disks/virtual_disks_usb.py
  libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py
  libvirt/tests/src/virtual_network/iface_target.py
  libvirt/tests/src/virtual_network/virtual_network_multivms.py
Labels: depend on

#3811 Fix the detach interface fail issue
  libvirt/tests/src/nwfilter/nwfilter_binding_list.py
Labels: minorfix

#3791 Add interface cases with acpi
  libvirt/tests/cfg/virtual_network/network_misc.cfg
  libvirt/tests/src/virtual_network/network_misc.py
Labels: depend on

#3755 sriov: Add a case to test max vfs
  libvirt/tests/cfg/sriov/sriov_scalability.cfg
  libvirt/tests/src/sriov/sriov_scalability.py
Labels: critical_case

#3765 sriov: Add 2 cases about network connections
  libvirt/tests/cfg/sriov/sriov_vf_pool.cfg
  libvirt/tests/src/sriov/sriov_vf_pool.py
Labels: depend on
