Repository autotest/tp-libvirt, pull requests merged in 2021-12, with the labels that each got.

#3901 migrate_vm: Add '-F' option to qemu-img create command
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#3899 controller_functional: Fix model for ppc
  libvirt/tests/src/controller/controller_functional.py
Labels: minorfix

#3908 virsh_detach_serial_device_alias: fix serial type ppc
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
Labels: minorfix

#3914 migrate_options_shared: Increase slow_speed for aarch64
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#3918 virsh_hypervisor_cpu_baseline: unsupport on ppc
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_baseline.cfg
  libvirt/tests/cfg/virtual_network/network_misc.cfg
Labels: minorfix

#3912 virsh_pool_autostart: Restart virtstoraged in modular deamons mode
  libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
Labels: minorfix

#3919 virsh_domxml_to_native: fix quote missing
  libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
Labels: minorfix

#3913 Update to check the result of virsh vol-download command
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
Labels: minorfix

#3921 Fix virt-admin connect uri for libvirtd daemon
  libvirt/tests/src/daemon/daemon_functional.py
Labels: minorfix

#3920 emulatorpin: Update the error message
  libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
Labels: minorfix

#3922 virsh_change_media_matrix: Fix pre_vm_state_paused TIMEOUT issue
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: minorfix

#3935 [minor fix] virsh_change_media_matrix: only running guest need to wait event
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: minorfix

#3947 filesystem_device: reload kvm for hugepages on s390x
  libvirt/tests/cfg/virtual_device/filesystem_device.cfg
Labels: minorfix

#3891 [filesystem_device]Add the cases of hotplug_unplug filesystem device
  libvirt/tests/cfg/virtual_device/filesystem_device.cfg
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: high_case

#3953 watchdog: relax qemu cmdline check
  libvirt/tests/src/virtual_device/watchdog.py
Labels: minorfix

#3955 input_devices: relax qemu cmdline check
  libvirt/tests/src/virtual_device/input_devices.py
Labels: minorfix

#3959 tpm_device: relax qemu cmdline check
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix

#3963 Update the qemu cmdline check
  libvirt/tests/src/virtual_network/mtu.py
Labels: minorfix

#3892 vdpa: Add a case to check network connectivity
  libvirt/tests/cfg/virtual_interface/connectivity_check.cfg
  libvirt/tests/src/virtual_interface/connectivity_check.py
  provider/interface/interface_base.py
Labels: high_case

#3968 Fix No more available PCI slots for virtual devices
  libvirt/tests/src/virtual_device/filesystem_device.py
Labels: minorfix

#3948 virsh_event: fix test cases for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
  libvirt/tests/src/virtual_device/watchdog.py
Labels: depend on

#3938 Fix managesave multi_guests case failure
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Labels: minorfix
