Repository autotest/tp-libvirt, pull requests merged in 2021-03, with the labels that each got.

#3328 v2v: fix incorrect disk count problem when vm has cdrom disk
  v2v/tests/src/function_test_xen.py
  v2v/tests/src/specific_kvm.py
  v2v/tests/src/v2v_options.py
Labels: depend on

#3351 v2v: update incorrect function name
  v2v/tests/src/function_test_xen.py
  v2v/tests/src/specific_kvm.py
  v2v/tests/src/v2v_options.py
Labels: minorfix

#3352 Remove incorrect skip aarch64 cases
  libvirt/tests/cfg/virtual_device/sound_device.cfg
  libvirt/tests/cfg/virtual_device/watchdog.cfg
Labels: minorfix

#3345 virtual_network: Fix iface_network for aarch64
  libvirt/tests/cfg/virtual_network/iface_network.cfg
Labels: minorfix

#3355 v2v: fix error comparing string in xen cfg file
  v2v/tests/cfg/function_test_xen.cfg
Labels: minorfix

#3354 v2v: fix incorrect parameter counts in test.error
  v2v/tests/src/function_test_xen.py
  v2v/tests/src/specific_kvm.py
Labels: minorfix

#3357 v2v: fix getting qemu-ga service failure in rhel6 guest
  v2v/tests/src/function_test_esx.py
Labels: minorfix

#3316 migrate_bandwidth: Run the stress tool to slow down migration process
  libvirt/tests/cfg/migration/migrate_bandwidth.cfg
  libvirt/tests/src/migration/migrate_bandwidth.py
Labels: depend on, minorfix

#3362 Fix transient feature failure on libvirt 6.0.0
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#3364 [virtio-transitional][s390x] add no filter on s390x
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk.cfg
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk_negative.cfg
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_nic.cfg
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_rng.cfg
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_serial.cfg
  libvirt/tests/cfg/virtio_transitional/virtio_transitional_vsock.cfg
Labels: minorfix

#3356 virsh_blockpull: Fix an error while converting raw
  libvirt/tests/cfg/virsh_cmd/domain/virsh_blockpull.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Labels: minorfix

#3368 controller_functional: remove multifunction test case for s390x
  libvirt/tests/cfg/controller/controller_functional.cfg
Labels: minorfix

#3369 v2v: fix boottype error on rhel9
  provider/v2v_vmcheck_helper.py
Labels: minorfix

#3344 controller_functional: fix vm define error
  libvirt/tests/cfg/controller/controller_functional.cfg
  libvirt/tests/src/controller/controller_functional.py
Labels: depend on

#3333 max_vcpus: Fix an issue in negative_test.ioapic_iommu
  libvirt/tests/cfg/cpu/max_vcpus.cfg
Labels: minorfix

#3360 Add cases for schedinfo
  libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
Labels: depend on

#3375 virsh_guestinfo: Test cleanup fix
  libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
Labels: minorfix

#3370 remote_with_unix: Complete fix the regex issue of unix connection test
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Labels: minorfix

#3307 Update controller of ppc vms to support hotplug/unplug of scsi device
  libvirt/tests/src/libvirt_scsi_hostdev.py
Labels: minorfix

#3299 Update controller of ppc vms to support hotplug/unplug
  libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
Labels: minorfix

#3359 Add case to validate disk cluster size set
  libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_disk.cfg
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Labels: MVP_RPL

#3401 Add the bug fixed version into the error message
  libvirt/tests/src/virtual_network/iface_rename.py
Labels: minorfix

#3394 virsh_boot: Update usb controller and loader path to the default
  libvirt/tests/cfg/bios/virsh_boot.cfg
Labels: minorfix

#3409 Ignore case distinctions in 'grep' for expected pattern
  libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Labels: minorfix
