Repository autotest/tp-libvirt, pull requests merged in 2021-11, with the labels that each got.

#3719 virsh_domdirtyrate_calc: Add cases of virsh domdirtyrate-calc
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domdirtyrate_calc.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
  spell.ignore
Labels: depend on

#3832 Remove hypervisor_cpu_baseline cases from pseries tests
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
Labels: minorfix

#3797 Remote Access:New case for a virsh connect polkit with a non-root user
  libvirt/tests/cfg/remote_access/virsh_non_root_polkit.cfg
  libvirt/tests/src/remote_access/virsh_non_root_polkit.py
Labels: depend on

#3860 v2v: fix the failed cases with error 'Not find cirrus device'
  provider/v2v_vmcheck_helper.py
Labels: minorfix

#3848 vcpu_nested: adapt for modular daemons
  libvirt/tests/cfg/cpu/vcpu_nested.cfg
  libvirt/tests/src/cpu/vcpu_nested.py
Labels: depend on

#3831 Fix gluster disk device detach event issue
  libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
Labels: minorfix

#3878 virsh_qemu_monitor_command: Update error message
  libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_command.py
Labels: minorfix

#3845 vDPA: Add a case to test domain lifecycle
  libvirt/tests/cfg/virtual_interface/domain_lifecycle.cfg
  libvirt/tests/src/virtual_interface/domain_lifecycle.py
  provider/interface/check_points.py
  provider/interface/vdpa_base.py
Labels: depend on, critical_case

#3877 Fix change media matrix event not received issue
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: minorfix

#3871 cpu_stats: Correct the cpu time checking
  libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
Labels: minorfix

#3887 virsh_vol_create.py: fix secret issue in storage volume with acl test
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
Labels: minorfix

#3886 migrate_vm: Fix variable 'uri' reference issue
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3890 virsh_boot.cfg: update error info of negative case
  libvirt/tests/cfg/bios/virsh_boot.cfg
Labels: minorfix

#3884 tpm_device: Expose error when test suite failed
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix

#3897 Start guest after reset guest PCI
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Labels: minorfix
