Repository autotest/tp-libvirt, pull requests merged in 2021-08, with the labels that each got.

#3678 controller_functional: skip pci_root for aarch64
  libvirt/tests/cfg/controller/controller_functional.cfg
Labels: minorfix

#3683 live_migration:fix err pattern
  libvirt/tests/cfg/migration/live_migration.cfg
Labels: minorfix

#3669 daemon: Add 3 libvirt-guests service related cases
  libvirt/tests/cfg/daemon/libvirt_guests_service.cfg
  libvirt/tests/src/daemon/libvirt_guests_service.py
Labels: critical_case, high_case

#3662 Storage: add clusterSize element cases to volume
  libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
Labels: depend on

#3694 vcpu_hotpluggable: Fix travis error
  libvirt/tests/src/cpu/vcpu_hotpluggable.py
Labels: minorfix

#3693 v2v: update fixed ovirt-engine version
  provider/v2v_vmcheck_helper.py
Labels: minorfix

#3651 Test the auto generated tap device name
  libvirt/tests/cfg/virtual_network/iface_target.cfg
  libvirt/tests/src/virtual_network/iface_target.py
Labels: depend on

#3698 graphics_functional: Update expected option
  libvirt/tests/src/graphics/graphics_functional.py
Labels: minorfix

#3616 Add Qos test for bridge type interface
  libvirt/tests/cfg/virtual_network/iface_bridge.cfg
  libvirt/tests/src/virtual_network/iface_bridge.py
  libvirt/tests/src/virtual_network/iface_network.py
Labels: depend on

#3699 graphics_functional: Remove extra steps for vnc
  libvirt/tests/cfg/graphics/graphics_functional.cfg
Labels: minorfix

#3582 Add blockpull with snapshots cases
  libvirt/tests/cfg/virtual_disks/virtual_disks_snapshot_blockpull.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_snapshot_blockpull.py
Labels: depend on

#3706 virsh_event: relax regex
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#3705 Fix one failure in snapshot blockcopy
  libvirt/tests/src/virtual_disks/virtual_disks_snapshot_blockpull.py
Labels: minorfix

#3702 Fix issue by switching image folder from tmp_data_dir to data_dir
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Labels: minorfix

#3710 Add 3 test cases about tap device connection check
  libvirt/tests/cfg/virtual_network/iface_bridge.cfg
  libvirt/tests/src/virtual_network/iface_bridge.py
Labels: depend on

#3724 Exclude s390x for vhostuser related test
  libvirt/tests/cfg/virtual_network/iface_options.cfg
Labels: minorfix

#3686 virsh_cmd:New cases added to test deprecated API
  libvirt/tests/cfg/virsh_cmd/host/virsh_deprecate_api.cfg
  libvirt/tests/src/virsh_cmd/host/virsh_deprecate_api.py
Labels: high_case

#3732 Revert "Exclude s390x for vhostuser related test"
  libvirt/tests/cfg/virtual_network/iface_options.cfg
Labels: minorfix

#3684 Add new cases of attaching lease
  libvirt/tests/cfg/lease_device.cfg
  libvirt/tests/src/lease_device.py
Labels: depend on

#3729 v2v: add version control to case win_bitlocker
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#3725 virsh_managedsave_extra: Fix IndexError: list index out of range
  libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_extra.py
Labels: minorfix
