Repository autotest/tp-libvirt, pull requests merged in 2022-09, with the labels that each got.

#4468 guestfs_add: Add a trailing newline when retreive contents
  libguestfs/tests/guestfs_add.py
Labels: minorfix

#4462 Remove allow_output_check option
  libvirt/tests/src/multifunction.py
Labels: minorfix

#4481 migration: Fixup no 'qemuProcessHandleMigrationStatus' issue
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#4484 Update the mount point to /tmp/mnt
  libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Labels: minorfix

#4486 migration: Fix service name error
  libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_precopy.cfg
Labels: minorfix

#4494 graphics_functional: Fix KeyError
  libvirt/tests/src/graphics/graphics_functional.py
Labels: minorfix

#4501 sriov: Fix an AttributeError
  libvirt/tests/cfg/sriov/vm_lifecycle/direct_passthrough_vm_lifecycle_start_destroy.cfg
  libvirt/tests/src/sriov/vm_lifecycle/direct_passthrough_vm_lifecycle_start_destroy.py
Labels: minorfix

#4504 Fix channel functional case failure on 390x
  libvirt/tests/cfg/channel/channel_functional.cfg
Labels: minorfix

#4503 Fix serial console failure on s390x
  libvirt/tests/cfg/serial/serial_pty_log.cfg
Labels: minorfix

#4497 Fix functional console invalid_chassisNr failure on 390x
  libvirt/tests/src/controller/controller_functional.py
Labels: minorfix

#4415 backingchain: add case for blockcommit with invalid top base
  libvirt/tests/cfg/backingchain/negative_scenario/blockcommit_invalid_top_base.cfg
  libvirt/tests/src/backingchain/negative_scenario/blockcommit_invalid_top_base.py
  provider/backingchain/blockcommand_base.py
Labels: modular_redesign

#4470 sriov: Add a plug_unplug case
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.py
  provider/sriov/sriov_base.py
Labels: modular_redesign

#4446 sriov: Add 2 network cases
  libvirt/tests/cfg/sriov/network/sriov_check_net_info_by_network_lifecycle_cmds.cfg
  libvirt/tests/cfg/sriov/network/sriov_define_or_start_network_with_pf_addr.cfg
  libvirt/tests/src/sriov/network/sriov_check_net_info_by_network_lifecycle_cmds.py
  libvirt/tests/src/sriov/network/sriov_define_or_start_network_with_pf_addr.py
  provider/sriov/sriov_base.py
Labels: modular_redesign

#4512 Update code according to review comments
  libvirt/tests/src/memory/memory_misc.py
Labels: minorfix

#4374 bios: Boot order test for ovmf guests
  libvirt/tests/cfg/bios/boot_order_ovmf.cfg
  libvirt/tests/src/bios/boot_order_ovmf.py
Labels: depend on

#4482 migration: Add case about auto converge
  libvirt/tests/cfg/migration/migration_efficiency/migration_vm_cpu_auto_converge.cfg
  libvirt/tests/src/migration/migration_efficiency/migration_efficiency.py
  provider/migration/migration_base.py
Labels: modular_redesign

#4471 sriov: Add a case to check various flags
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_with_flags.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_with_flags.py
  provider/sriov/sriov_base.py
Labels: modular_redesign

#4521 fix none type get source file
  provider/virtual_disk/disk_base.py
Labels: minorfix

#4523 sriov: Update to scp correct xml file
  libvirt/tests/src/sriov/failover/sriov_failover_migration.py
Labels: minorfix

#4480 migration: Add case for maxdowntime
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_maxdowntime.cfg
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_vm_cpu_auto_converge.cfg
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy.cfg
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy_abort.cfg
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy_unsupported_feature_combinations.cfg
  libvirt/tests/src/migration/migration_performance_tuning/migration_maxdowntime.py
  libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
  libvirt/tests/src/migration/migration_performance_tuning/migration_zerocopy.py
  provider/migration/migration_base.py
Labels: modular_redesign

#4479 migration: Add case for precopy bandwidth
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_precopy_bandwidth.cfg
  libvirt/tests/src/migration/migration_performance_tuning/migration_precopy_bandwidth.py
  provider/migration/migration_base.py
Labels: modular_redesign

#4527 migration: Fix wrong transport type
  libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_wrong_cert_configuration.cfg
Labels: minorfix

#4526 virsh_detach_serial_device_alias: fix_early_unplug
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
Labels: minorfix

#4477 migration: Add case for memory compression
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_memory_compression.cfg
  libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
Labels: modular_redesign

#4478 migration: Add case for timeout action
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_timeout_action.cfg
  libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
  provider/migration/migration_base.py
Labels: depend on, modular_redesign

#4531 libvirtd.py: Fix arguments error
  libvirt/tests/src/libvirtd/libvirtd.py
Labels: minorfix

#4533 virsh_connect: Fix client_ip parameter issue
  libvirt/tests/src/virsh_cmd/virsh_connect.py
Labels: minorfix

#4489 sriov: Add a hostdev attach/detach test
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_special_situations.cfg
  libvirt/tests/cfg/sriov/sriov_ro_sysfs.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_special_situations.py
  libvirt/tests/src/sriov/sriov_ro_sysfs.py
  provider/sriov/sriov_base.py
Labels: modular_redesign

#4496 sriov: Add a test to check iommu support
  libvirt/tests/cfg/sriov/capabilities/sriov_capabilities_iommu_support.cfg
  libvirt/tests/cfg/sriov/sriov_capabilities.cfg
  libvirt/tests/src/sriov/capabilities/sriov_capabilities_iommu_support.py
  libvirt/tests/src/sriov/sriov_capabilities.py
Labels: modular_redesign

#4432 backingchain: add case for blockcoopy with --synchronous --writes
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_syncwrites_option.cfg
  libvirt/tests/cfg/backingchain/blockcopy_options.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_syncwrites_option.py
  libvirt/tests/src/backingchain/blockcopy_options.py
Labels: modular_redesign

#4509 sriov: Add a negative test about attaching/detaching hostdev
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_with_unsupported_settings.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_with_unsupported_settings.py
Labels: modular_redesign

#4508 sriov: Add a test to check the network connections
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_check_connections.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_check_connections.py
Labels: modular_redesign

#4502 Update cases for new iothreadids class
  libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin_mix.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py
  libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py
  libvirt/tests/src/virsh_cmd/domain/virsh_iothreadinfo.py
  libvirt/tests/src/virsh_cmd/domain/virsh_iothreadpin.py
Labels: depend on

#4487 Update reference of xml classes Serial, Console and Channel
  libvirt/tests/src/channel/channel_functional.py
  libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
  libvirt/tests/src/serial/serial_functional.py
  libvirt/tests/src/serial/serial_pty_log.py
  libvirt/tests/src/svirt/default_dac_check.py
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
Labels: depend on

#4545 npiv: fix a 'no available lun' issue
  libvirt/tests/src/npiv/npiv_hostdev_passthrough.py
Labels: minorfix

#4472 libvirtd: Ignore PVR err str for aarch64
  libvirt/tests/cfg/libvirtd/libvirtd.cfg
  libvirt/tests/src/libvirtd/libvirtd.py
Labels: depend on

#4461 backingchain: add case for blockpull with relative path
  libvirt/tests/cfg/backingchain/blockpull/blockpull_relative_path.cfg
  libvirt/tests/src/backingchain/blockpull/blockpull_relative_path.py
  provider/backingchain/blockcommand_base.py
  provider/virtual_disk/disk_base.py
Labels: modular_redesign

#4500 iothread: new case for thread pool
  libvirt/tests/cfg/cpu/iothread.cfg
  libvirt/tests/src/cpu/iothread.py
Labels: depend on

#4456 backingchain: add case for blockcopy with blockdev option
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_blockdev_option.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_blockdev_option.py
  provider/backingchain/blockcommand_base.py
  provider/virtual_disk/disk_base.py
Labels: modular_redesign

#4525 backingchain: add case for blockcopy with invalid dest file
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_invalid_destination.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_invalid_destination.py
Labels: modular_redesign

#4516 backingchain: add case for blockjob with bandwidth
  libvirt/tests/cfg/backingchain/blockjob/blockjob_with_bandwidth_option.cfg
  libvirt/tests/src/backingchain/blockjob/blockjob_with_bandwidth_option.py
Labels: modular_redesign

#4499 blockcommit relative: update new disk xml with backingstore
  libvirt/tests/cfg/backingchain/blockcommit/blockcommit_relative_path.cfg
  libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py
Labels: modular_redesign

#4507 backingchain: add case for blockjob with raw option
  libvirt/tests/cfg/backingchain/blockjob/blockjob_with_raw_option.cfg
  libvirt/tests/src/backingchain/blockjob/blockjob_with_raw_option.py
Labels: modular_redesign

#4537 migration: Fix undefine vm issue
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
Labels: minorfix

#4447 backingchain: add case for blockpull with async option
  libvirt/tests/cfg/backingchain/blockpull/blockpull_with_async.cfg
  libvirt/tests/src/backingchain/blockpull/blockpull_with_async.py
  provider/backingchain/blockcommand_base.py
Labels: modular_redesign

#4541 migration: Fix rng issue
  libvirt/tests/src/migration/migrate_with_virtual_devices.py
  spell.ignore
Labels: minorfix

#4560 iothread: fix var missing
  libvirt/tests/cfg/cpu/iothread.cfg
Labels: minorfix

#4562 move negative case to negative folder
  libvirt/tests/cfg/backingchain/negative_scenario/blockcopy_with_invalid_destination.cfg
  libvirt/tests/cfg/backingchain/negative_scenario/blockjob_with_invalid_operation.cfg
  libvirt/tests/src/backingchain/negative_scenario/blockcopy_with_invalid_destination.py
  libvirt/tests/src/backingchain/negative_scenario/blockjob_with_invalid_operation.py
Labels: minorfix
