Repository autotest/tp-libvirt, pull requests merged in 2022-03, with the labels that each got.

#4068 sriov: Extend sleep time before checking initialization of VFs
  libvirt/tests/src/sriov/sriov.py
Labels: minorfix

#4046 tpm_device: add active_pcr_banks test
  libvirt/tests/cfg/virtual_device/tpm_device.cfg
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: depend on

#3978 Add define guest with scsi LUN device --BZ 1078126, 1201143 case
  libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
Labels: high_case

#4047 blockresize: add blockresize case
  libvirt/tests/cfg/backingchain/blockresize.cfg
  libvirt/tests/src/backingchain/blockresize.py
  provider/backingchain/check_functions.py
Labels: depend on

#4088 sriov: Update string split separator for check_numa function
  libvirt/tests/src/sriov/sriov.py
Labels: minorfix

#4096 update file after rename utils_secret.py to libvirt_secret.py
  libvirt/tests/src/backingchain/virtual_disks_snapshot_blockpull.py
  libvirt/tests/src/embedded_qemu/embedded_qemu.py
  libvirt/tests/src/incremental_backup/incremental_backup_event_monitor.py
  libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
  libvirt/tests/src/migration/migrate_options_shared.py
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy_xml.py
  libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
  libvirt/tests/src/virt_cmd/virt_xml_validate.py
  libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Labels: depend on

#4060 Fix virtual_disks gluster default_pool cases failures
  libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
Labels: minorfix

#4090 Fix detach-disk event not found issue when option contains "--config"
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#4107 virsh_vol_create_from.py: update the image size to fix scsi/iscsi issue
  libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
Labels: minorfix

#4105 v2v: enable crypto policy to LEGACY for old guests
  v2v/tests/cfg/convert_from_file.cfg
  v2v/tests/cfg/convert_vm_to_libvirt.cfg
  v2v/tests/cfg/convert_vm_to_ovirt.cfg
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/cfg/specific_kvm.cfg
  v2v/tests/src/convert_from_file.py
  v2v/tests/src/convert_vm_to_libvirt.py
  v2v/tests/src/convert_vm_to_ovirt.py
  v2v/tests/src/function_test_esx.py
  v2v/tests/src/specific_kvm.py
  v2v/tests/src/v2v_options.py
Labels: depend on

#4097 numa_memory_spread: use first numa node with mem
  libvirt/tests/cfg/numa/numa_memory_spread.cfg
Labels: minorfix

#4121 Fix no more available PCI slots for interface device
  libvirt/tests/src/libvirt_hooks.py
Labels: minorfix

#4095 numa_memory: fix foreground libvirtd start
  libvirt/tests/cfg/numa/numa_memory.cfg
  libvirt/tests/src/numa/numa_memory.py
Labels: depend on

#4123 nmi_test: Add debug log
  libvirt/tests/src/guest_kernel_debugging/nmi_test.py
Labels: minorfix

#4130 [minor fix] numa_memory_spread: Fix wrong neighbour node
  libvirt/tests/src/numa/numa_memory_spread.py
Labels: minorfix

#4116 numa_memory: fix bitmap error
  libvirt/tests/src/numa/numa_memory.py
Labels: minorfix
