Repository autotest/tp-libvirt, pull requests merged in 2022-11, with the labels that each got.

#4615 remote_access: fix not assignment
  libvirt/tests/src/remote_access/remote_access.py
Labels: minorfix

#4536 numa_memory: add checkpoints for VMStartError
  libvirt/tests/cfg/numa/numa_memory.cfg
  libvirt/tests/src/numa/numa_memory.py
Labels: minorfix, depend on

#4604 sriov: Add a case to test vIOMMU device's alias
  libvirt/tests/cfg/sriov/vIOMMU/sriov_iommu_alias.cfg
  libvirt/tests/src/sriov/vIOMMU/sriov_iommu_alias.py
  provider/sriov/sriov_base.py
Labels: depend on

#4617 migration: Update error message
  libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
Labels: minorfix

#4616 migration: Add case about specified tls hostname
  libvirt/tests/cfg/migration/migrate_storage.cfg
  libvirt/tests/src/migration/migrate_storage.py
Labels: migration

#4618 migration: Update error message
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
Labels: minorfix

#4587 numa_memory_spread: extend timeout for memhog
  libvirt/tests/src/numa/numa_memory_spread.py
Labels: minorfix

#4608 sriov: Add a case about nodedev reatach/detach
  libvirt/tests/cfg/sriov/nodedev/sriov_nodedev_reattach_detach.cfg
  libvirt/tests/src/sriov/nodedev/sriov_nodedev_reattach_detach.py
Labels: modular_redesign

#4594 fix cannot acquire state change lock
  libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Labels: minorfix

#4622 Replace nvram_template with nvram_attrs
  libvirt/tests/src/bios/boot_integration.py
  libvirt/tests/src/bios/virsh_boot.py
Labels: depend on

#4629 sriov: Add a case of attaching hostdev interface
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface.py
Labels: modular_redesign

#4563 backingchain:add case for blockcopy with disk driver elements
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.py
Labels: modular_redesign

#4579 backingchain: add case for blockpull with invalid base image
  libvirt/tests/cfg/backingchain/negative_scenario/blockpull_with_invalid_base.cfg
  libvirt/tests/src/backingchain/negative_scenario/blockpull_with_invalid_base.py
Labels: modular_redesign

#4610 Backingchain: add new case for blockcopy with granularity and buf-size
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_granularity_buf_size_option.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_granularity_buf_size_option.py
Labels: modular_redesign

#4621 svirt: Enable selinux_relabel test for aarch64
  libvirt/tests/cfg/svirt/selinux_relabel.cfg
Labels: minorfix

#4627 virtual_disk: Wait for device is ready on guest after attach-device
  libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
Labels: minorfix

#4642 sriov: Update to check if the vm interface exists
  provider/sriov/sriov_base.py
Labels: minorfix

#4637 usb_device: remove necessary package
  libvirt/tests/cfg/usb_device.cfg
Labels: minorfix

#4577 backingchain: add case for blockjob pivot after irregular operation
  libvirt/tests/cfg/backingchain/blockjob/blockjob_pivot_after_irregular_operations.cfg
  libvirt/tests/src/backingchain/blockjob/blockjob_pivot_after_irregular_operations.py
Labels: modular_redesign

#4595 Add the case of domdirtyrate_calc
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domdirtyrate_calc.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
Labels: depend on

#4630 virsh_start: Just check the audit log generated in this case
  libvirt/tests/src/virsh_cmd/domain/virsh_start.py
Labels: minorfix

#4649 graphics_functional: fix not assign address
  libvirt/tests/cfg/graphics/graphics_functional.cfg
  libvirt/tests/src/graphics/graphics_functional.py
Labels: minorfix

#4652 graphics_functional: fix spice_tls missing
  libvirt/tests/cfg/graphics/graphics_functional.cfg
Labels: minorfix

#4654 memory_misc: disable test on s390x
  libvirt/tests/cfg/memory/memory_misc.cfg
Labels: minorfix

#4601 backingchain:blockcopy with bandwidth option
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_bandwidth.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_bandwidth.py
Labels: modular_redesign
