Repository autotest/tp-libvirt, pull requests merged in 2022-07, with the labels that each got.

#4349 Refactor code for interface virtualport change
  libvirt/tests/src/virtual_network/iface_coalesce.py
Labels: depend on

#4352 tpm_device: fix nvram find and vm start failures
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: minorfix, critical_case

#4351 Set debug=True for virsh.net_dumpxml tests
  libvirt/tests/src/virsh_cmd/network/virsh_net_dumpxml.py
Labels: minorfix

#4306 virsh_nodeinfo: fix incorrect checking
  libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Labels: depend on

#4361 Fix for func entry update
  libvirt/tests/src/cpu/vcpu_affinity.py
  libvirt/tests/src/numa/numa_numatune_cpu.py
  libvirt/tests/src/virsh_cmd/host/virsh_nodecpumap.py
  libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
  libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Labels: minorfix, depend on

#4346 sriov: Add a negative lifecycle case
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.cfg
  libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.py
Labels: depend on

#4340 Update vf_list reference of sriov tests
  libvirt/tests/src/sriov/sriov.py
Labels: depend on

#4277 Newly add test cases to cover new feature support in virsh snapshot
  libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_mode.cfg
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_mode.py
Labels: high_case

#4369 Disable osinfo detect in virt-install
  libvirt/tests/src/svirt/svirt_virt_install.py
Labels: minorfix

#4317 migration: Remove qemu command line checking
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#4386 pcibridge: fix incorrect index
  libvirt/tests/cfg/controller/pcibridge.cfg
  libvirt/tests/src/controller/pcibridge.py
Labels: minorfix

#4385 pcie_controllers: fix incorrect print format
  libvirt/tests/cfg/controller/pcie_controllers.cfg
  libvirt/tests/src/controller/pcie_controllers.py
Labels: minorfix

#4382 controller_functional: fix incorrect num
  libvirt/tests/src/controller/controller_functional.py
Labels: minorfix

#4390 blockcommand_base: remove existed snap file
  provider/backingchain/blockcommand_base.py
Labels: minorfix
