Repository autotest/tp-libvirt, pull requests merged in 2022-05, with the labels that each got.

#4173 Add cases to cover hotplug rbd disk with enabled authentication as vi…
  libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
Labels: minorfix

#4183 Fix the failures when running negative tests
  libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
Labels: minorfix

#4188 virsh_detach_device_alias.py: fix detach device alias get params error
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Labels: minorfix

#4185 migration: Update to recover the source host's hosts file
  libvirt/tests/src/migration/live_migration.py
Labels: minorfix

#4187 domblkthreshold.py: fix get no event after domblkthreshold
  libvirt/tests/src/backingchain/domblkthreshold.py
Labels: minorfix

#4210 serial_pty_log: Extend the timeout for getting login prompt
  libvirt/tests/src/serial/serial_pty_log.py
Labels: minorfix

#4198 numa_memory_spread: no need this package
  libvirt/tests/src/numa/numa_memory_spread.py
Labels: minorfix

#4211 numa_memory: fix usage for check_logfile
  libvirt/tests/src/numa/numa_memory.py
  libvirt/tests/src/numa/numa_memory_migrate.py
Labels: depend on

#4217 cpu: Remove pm setting
  libvirt/tests/src/libvirt_vcpu_plug_unplug.py
Labels: minorfix

#4119 numa_memory_migrate: enhance to use available numa node
  libvirt/tests/cfg/numa/numa_memory_migrate.cfg
  libvirt/tests/src/numa/numa_memory_migrate.py
Labels: depend on

#4118 virsh_numatune: fix_numa_nodeset
  libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
Labels: depend on

#4171 nvdimm: add case for pmem and alignsize and readonnly
  libvirt/tests/cfg/memory/nvdimm.cfg
  libvirt/tests/src/memory/nvdimm.py
  spell.ignore
Labels: depend on

#4225 vsock: Extend event_timeout for detach_device_alias
  libvirt/tests/src/virtual_device/vsock.py
Labels: minorfix

#4233 svirt:Destroy vm after test to avoid permission issue
  libvirt/tests/src/svirt/dac_nfs_save_restore.py
  libvirt/tests/src/svirt/dac_start_destroy.py
Labels: minorfix

#4169 sriov: Add a vm lifecycle case
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.cfg
  libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.py
  provider/sriov/check_points.py
  provider/sriov/sriov_base.py
Labels: depend on

#4234 v2v:correct rhel8_dev_short_id
  v2v/tests/cfg/convert_vm_to_libvirt.cfg
Labels: minorfix

#4215 usb_device: fix with compatible match
  libvirt/tests/src/usb_device.py
Labels: minorfix

#4071 Add case to cover starting guest with multiple disks when device mapp…
  libvirt/tests/cfg/virtual_disks/virtual_disks_device_mapper.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_device_mapper.py
Labels: high_case
