Repository autotest/tp-libvirt, pull requests merged in 2022-06, with the labels that each got.

#4240 migration_base: Fix a name error
  provider/migration/migration_base.py
Labels: minorfix

#4243 v2v: fix nonetype iteration issue
  provider/v2v_vmcheck_helper.py
Labels: minorfix

#4239 Add new case of memorybacking
  libvirt/tests/cfg/memory/memory_misc.cfg
  libvirt/tests/src/memory/memory_misc.py
Labels: depend on

#4230 Guest agent: Add a case to check lifecycle's events
  libvirt/tests/cfg/guest_agent/agent_lifecycle.cfg
  libvirt/tests/cfg/guest_agent/guest_agent.cfg
  libvirt/tests/src/guest_agent/agent_lifecycle.py
  libvirt/tests/src/guest_agent/guest_agent.py
Labels: high_case, depend on

#4182 Add case for modular redesign migration
  libvirt/tests/cfg/migration/network_data_transports/migration_network_data_transports_tcp.cfg
  libvirt/tests/src/migration/network_data_transports/migration_network_data_transports_tcp.py
  provider/migration/base_steps.py
  provider/migration/migration_base.py
Labels: depend on

#4254 memory_misc:Remove unsupported tests from other archs
  libvirt/tests/cfg/memory/memory_misc.cfg
Labels: minorfix

#4255 fix to use --nvram in virsh undefine
  libvirt/tests/src/backingchain/virtual_disks_blockcopy_options.py
  libvirt/tests/src/lxc/lxc_life_cycle.py
  libvirt/tests/src/multifunction.py
  libvirt/tests/src/numa/numa_preferred_undefine.py
  libvirt/tests/src/passthrough/pci/vfio.py
  libvirt/tests/src/svirt/svirt_start_destroy.py
  libvirt/tests/src/svirt/svirt_undefine_define.py
  libvirt/tests/src/virsh_cmd/domain/virsh_define.py
  libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
  libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py
  libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py
  libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
  libvirt/tests/src/virsh_cmd/domain/virsh_vcpucount.py
  libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py
  libvirt/tests/src/virtual_disks/virtual_disks_luks.py
  libvirt/tests/src/virtual_network/iface_unprivileged.py
Labels: depend on

#4203 Add case to attach/detach interface for bridge type using openvswitch
  libvirt/tests/cfg/virtual_network/iface_ovs.cfg
  libvirt/tests/src/virtual_network/iface_ovs.py
Labels: high_case

#4270 virtual_disks.ccw_addr: disable tests on s390x
  libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
Labels: minorfix

#4268 virsh_setmem: fix cmdline for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
Labels: minorfix

#4266 memory_discard: disable tests on s390x
  libvirt/tests/cfg/memory/memory_discard.cfg
Labels: minorfix

#4267 memory_misc: disable test cases on s390x
  libvirt/tests/cfg/memory/memory_misc.cfg
Labels: minorfix

#4265 hmat: disable tests on s390x
  libvirt/tests/cfg/memory/hmat.cfg
Labels: minorfix

#4264 libvirt_cputune: disable tests on s390x
  libvirt/tests/cfg/libvirt_cputune.cfg
Labels: minorfix

#4262 libvirt_vcpu_plug_unplug: disable test on s390x
  libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
Labels: minorfix

#4272 virsh_managedsave:Turn on --nvram option to undefine command
  libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Labels: minorfix

#4273 migration: Fix a TypeError
  libvirt/tests/src/migration/network_data_transports/migration_network_data_transports_tcp.py
  provider/migration/migration_base.py
Labels: minorfix

#4275 Fix attach device matrix failure due to vm.undefine
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
Labels: minorfix

#4276 Fix virsh change_media_matrix cases failure due to vm.undefine
  libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Labels: minorfix

#4278 virsh_detach_device_alias.py:fix detach iface alias error
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Labels: minorfix

#4284 Fix attach detach_disk matrix cases failure due to undefine VM
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk_matrix.py
Labels: minorfix

#4245 Added the case of tcp_min_ssf
  libvirt/tests/cfg/remote_access/remote_with_tcp.cfg
  libvirt/tests/src/remote_access/remote_access.py
Labels: depend on

#4257 virttools/virt_install.kernel_cmdline: fix test condition
  virttools/tests/src/virt_install/kernel_cmdline.py
Labels: minorfix

#4315 virsh_create: fix undefine with nvram
  libvirt/tests/src/virsh_cmd/domain/virsh_autostart.py
  libvirt/tests/src/virsh_cmd/domain/virsh_create.py
  libvirt/tests/src/virsh_cmd/domain/virsh_desc.py
Labels: minorfix

#4316 Update the vm.undefine() to adapt to ovmf guest
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
Labels: minorfix

#4309 Update test cases to adapt to updated NetworkXML class
  libvirt/tests/src/daemon/crash_regression.py
  libvirt/tests/src/libvirt_network_bandwidth.py
  libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
  libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
  libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
  libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
  libvirt/tests/src/virtual_network/iface_network.py
Labels: depend on

#4322 Add "--nvram" to the virsh.remove_domain()
  libvirt/tests/src/virtual_network/iface_options.py
Labels: minorfix

#4325 Add "--nvram" to virsh.remove_domain()
  libvirt/tests/src/virtual_network/iface_network.py
Labels: minorfix
