Repository autotest/tp-libvirt, pull requests merged in 2022-04, with the labels that each got.

#4143 fix device_removed event not found in blockresize
  libvirt/tests/src/backingchain/blockresize.py
Labels: minorfix

#4007 nodedev_persistence: add test case for nodedev persistent setup API
  libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_persistence_mdev.cfg
  libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_persistence_mdev.py
  spell.ignore
Labels: depend on

#4145 v2v: update the setting of LIBGEUSTFS_BACKEND
  v2v/tests/src/function_test_esx.py
  v2v/tests/src/function_test_xen.py
  v2v/tests/src/specific_kvm.py
Labels: depend on

#4073 sriov: Add 3 cases
  libvirt/tests/cfg/sriov/sriov_attach_hostdev.cfg
  libvirt/tests/src/sriov/sriov_attach_hostdev.py
  provider/sriov/check_points.py
Labels: depend on

#4161 virsh_non_root_polkit: Change 'uri' to 'virsh_uri'
  libvirt/tests/cfg/remote_access/virsh_non_root_polkit.cfg
  libvirt/tests/src/remote_access/virsh_non_root_polkit.py
Labels: minorfix

#4164 provider/vfio/ccw: improve logging
  provider/vfio/ccw.py
Labels: minorfix

#4166 Fix virtual network err msg failure
  libvirt/tests/cfg/virtual_network/network_misc.cfg
Labels: minorfix

#4165 Add more error message for mapping new result
  libvirt/tests/cfg/bios/virsh_boot.cfg
Labels: minorfix

#4115 memory: Add cases about virtio-mem device
  libvirt/tests/cfg/memory/memory_attach_device.cfg
  libvirt/tests/cfg/memory/memory_update_device.cfg
  libvirt/tests/src/memory/memory_attach_device.py
  libvirt/tests/src/memory/memory_update_device.py
Labels: high_case, depend on

#4139 remote_with_unix: Fix UNIX connection issues
  libvirt/tests/cfg/remote_access/remote_with_unix.cfg
  libvirt/tests/src/remote_access/remote_access.py
Labels: depend on
