Repository autotest/tp-libvirt, pull requests merged in 2022-01, with the labels that each got.

#3893 vDPA: Add a case to test memory hotplug
  libvirt/tests/cfg/virtual_interface/hotplug_mem.cfg
  libvirt/tests/src/virtual_interface/hotplug_mem.py
Labels: high_case

#3915 memory/allocpages: test huge pages can be allocated on s390x
  libvirt/tests/cfg/memory/allocpages.cfg
  libvirt/tests/src/memory/allocpages.py
Labels: depend on

#3974 [minor fix] virsh_undefine: skip no_option test for aarch64
  libvirt/tests/cfg/virsh_cmd/domain/virsh_undefine.cfg
Labels: minorfix

#3973 iothread: Fix detach disk error
  libvirt/tests/src/cpu/iothread.py
Labels: minorfix

#3967 Fix the setmem case qemu-cmd-line match error
  libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
Labels: minorfix

#3979 boot_integration: Update seabios file
  libvirt/tests/cfg/bios/boot_integration.cfg
Labels: minorfix

#3982 virsh_event: Fix detach disk error
  libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Labels: minorfix

#3984 vcpu_feature: Update error message for host_without_cr8legacy
  libvirt/tests/cfg/cpu/vcpu_feature.cfg
Labels: minorfix

#3989 virsh_migrate_option_mix: Update vnc pwd
  libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_option_mix.cfg
Labels: minorfix

#3987 migrate_vm: Fix variable 'remote_session' reference issue
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#3985 Fix local variable 'ori_pid_libvirtd' referenced before assignment issue
  libvirt/tests/src/virtual_disks/virtual_disks_ccw_addr.py
Labels: minorfix

#4009 video_devices: Fix log reuse issue
  libvirt/tests/src/virtual_device/video_devices.py
Labels: minorfix

#4018 nodedev: Fix nodedev driver issue
  libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
Labels: minorfix

#4020 v2v: fix some spell errors
  v2v/tests/cfg/function_test_esx.cfg
  v2v/tests/cfg/nbdkit/nbdkit.cfg
  v2v/tests/cfg/v2v_options.cfg
  v2v/tests/src/function_test_esx.py
  v2v/tests/src/nbdkit/nbdkit.py
  v2v/tests/src/v2v_options.py
Labels: minorfix

#3923 virttools: add new test type and virt-install test
  provider/vfio/ccw.py
  spell.ignore
  virttools/README.md
  virttools/tests/cfg/virt_install/hostdev_mdev.cfg
  virttools/tests/src/virt_install/hostdev_mdev.py
Labels: depend on
