Repository autotest/tp-libvirt, pull requests merged in 2022-10, with the labels that each got.

#4435 Newly added cases to cover:do blockresize for device which has backing chain element
  libvirt/tests/cfg/virtual_disks/virtual_disks_snapshot_blockresize.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_snapshot_blockresize.py
Labels: high_case

#4429 Add case: start VM with optional startupPolicy
  libvirt/tests/cfg/virtual_disks/virtual_disks_optional_startuppolicy.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_optional_startuppolicy.py
Labels: high_case

#4534 Add case of selinux relabel
  libvirt/tests/cfg/svirt/selinux_relabel.cfg
  libvirt/tests/src/svirt/selinux_relabel.py
Labels: depend on

#4570 fix rm folder error
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_blockdev_option.py
Labels: minorfix

#4568 fix miss snap in snap list
  provider/backingchain/blockcommand_base.py
Labels: minorfix

#4552 sriov: Add a case about attaching a hostdev interface from network
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_from_network.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_from_network.py
Labels: modular_redesign

#4553 virtual_disk: Fix nbd server is not ready
  libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Labels: minorfix

#4574 controller_functional: fix error message match
  libvirt/tests/cfg/controller/controller_functional.cfg
  libvirt/tests/cfg/controller/pcibridge.cfg
Labels: minorfix

#4535 numa_memory: fix incorrect numa node usage
  libvirt/tests/cfg/numa/numa_memory.cfg
  libvirt/tests/src/numa/numa_memory.py
Labels: depend on

#4555 sriov: Add a case about hotplug a released hostdev
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_released_hostdev.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_released_hostdev.py
Labels: modular_redesign

#4575 Fix blockpull failure due to low timeout value
  libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Labels: minorfix

#4590 disk_base.py: fix blockcommit failed issue for block disk
  provider/virtual_disk/disk_base.py
Labels: minorfix

#4459 migration: Add case for poweroff vm
  libvirt/tests/cfg/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.cfg
  libvirt/tests/src/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.py
Labels: modular_redesign

#4543 migration: Add case about kill libvirt daemon
  libvirt/tests/cfg/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.cfg
  libvirt/tests/src/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.py
  provider/migration/migration_base.py
Labels: depend on, modular_redesign

#4558 migration: Add case about recover migration
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/no_paused_during_recover_migration.cfg
  libvirt/tests/src/migration/live_migration.py
  libvirt/tests/src/migration/migrate_event.py
  libvirt/tests/src/migration/migrate_service_control.py
  libvirt/tests/src/migration/migrate_with_various_hostname.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/no_paused_during_recover_migration.py
  provider/migration/base_steps.py
  provider/migration/migration_base.py
Labels: modular_redesign

#4551 sriov: Add a case about attaching/detaching a hostdev interface with flags
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_with_flags.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_with_flags.py
Labels: modular_redesign

#4554 sriov: Add a case to attach/detach a hostdev interface
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_special_situations.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_special_situations.py
Labels: modular_redesign

#4602 migration: Remove check drive-mirror/nbd-server
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix

#4603 virttools: Change installation tree location
  virttools/tests/cfg/virt_install/kernel_cmdline.cfg
Labels: minorfix

#4605 fix set_disk_xml function duplicate
  provider/virtual_disk/disk_base.py
Labels: minorfix

#4606 pcie_controller_hotplug_option: rename file
  libvirt/tests/cfg/controller/pcie_controller_hotplug_option.cfg
  libvirt/tests/src/controller/pcie_controller_hotplug_option.py
Labels: minorfix

#4593 fix missing ceph config file
  libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py
  libvirt/tests/src/backingchain/blockpull/blockpull_relative_path.py
  provider/virtual_disk/disk_base.py
Labels: minorfix

#4612 remote_access: fix UnboundLocalError
  libvirt/tests/src/remote_access/remote_access.py
Labels: minorfix
