Repository autotest/tp-libvirt, pull requests merged in 2022-12, with the labels that each got.

#4661 v2v:add ESXi8.0 conf info
  v2v/tests/cfg/convert_vm_to_libvirt.cfg
  v2v/tests/cfg/convert_vm_to_ovirt.cfg
Labels: depend on

#4666 virsh.detach_serial_device_alias: disable on s390
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
Labels: minorfix

#4634 sriov: Add a case
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_interface_to_vm_with_vf.cfg
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_interface_to_vm_with_vf.py
Labels: modular_redesign

#4619 migration: Add case about pause/recover migration
  libvirt/tests/cfg/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.cfg
  libvirt/tests/cfg/migration/migrate_service_control.cfg
  libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.cfg
  libvirt/tests/src/migration/migrate_service_control.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration.py
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.py
  provider/migration/base_steps.py
  provider/migration/migration_base.py
Labels: depend on, modular_redesign

#4650 graphics_functional: add network case
  libvirt/tests/cfg/graphics/graphics_functional.cfg
  libvirt/tests/src/graphics/graphics_functional.py
Labels: depend on

#4584 migration: Add case about pause migration
  libvirt/tests/cfg/migration/live_migration.cfg
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.cfg
  libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.py
  provider/migration/migration_base.py
Labels: depend on, modular_redesign

#4645 Backingchain: add case to do hotplug test
  libvirt/tests/cfg/backingchain/hotplug_test/hot_un_plug.cfg
  libvirt/tests/src/backingchain/hotplug_test/hot_un_plug.py
Labels: modular_redesign

#4628 Backingchain: add new case for blockjob with --async
  libvirt/tests/cfg/backingchain/blockjob/blockjob_with_async_option.cfg
  libvirt/tests/src/backingchain/blockjob/blockjob_with_async_option.py
Labels: modular_redesign

#4679 iface_update:Update error message of negative test
  libvirt/tests/cfg/virtual_network/iface_update.cfg
Labels: minorfix

#4632 backingchain:add case for domblkthreshold with backing chain element
  libvirt/tests/cfg/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.cfg
  libvirt/tests/src/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.py
  provider/backingchain/blockcommand_base.py
Labels: modular_redesign

#4646 backingchain: add case for blockcopy with different qcow2 properities
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_qcow2_properties.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_different_qcow2_properties.py
  provider/backingchain/blockcommand_base.py
Labels: modular_redesign

#4688 virsh_cpu_xml: Change cpu xml back to original file for negative test
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
Labels: minorfix

#4339 snapshot: Make sure the guest boot successfully before snapshot-create-as
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
Labels: minorfix

#4691 backingchain: Update the disk attribute according to the modification of avocado-vt
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.cfg
Labels: minorfix
