Repository autotest/tp-libvirt, pull requests merged in 2023-06, with the labels that each got.

#4929 migration: Update error message
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy_unsupported_feature_combinations.cfg
Labels: minorfix

#4894 memory_binding_with_emulator_thread: add case
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
Labels: depend on

#4823 numa_topology_with_numa_distance: add case
  libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_numa_distance.cfg
  libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_numa_distance.py
Labels: modular_redesign

#4940 save_with_options:Update target pattern to search for
  libvirt/tests/cfg/save_and_restore/save_with_options.cfg
Labels: minorfix

#4947 Fix domain_life_cycle.undefine_domain.positive.wipe_storage case failure
  libvirt/tests/cfg/domain_life_cycle/create_destroy_domain.cfg
  libvirt/tests/src/domain_life_cycle/create_destroy_domain.py
Labels: minorfix

#4912 memory_binding_setting: add case
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_setting.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
  provider/numa/numa_base.py
Labels: depend on

#4871 numa_topology_with_cpu_topology: add case
  libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_cpu_topology.cfg
  libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_cpu_topology.py
Labels: depend on, modular_redesign

#4903 migration: Add case about domjobinfo
  libvirt/tests/cfg/migration/async_job/migration_domjobinfo.cfg
  libvirt/tests/src/migration/async_job/migration_domjobinfo.py
  provider/migration/migration_base.py
Labels: depend on

#4958 fix data transfer case not find host msg
  libvirt/tests/src/chardev/connection_and_operation/data_transfer.py
Labels: minorfix

#4878 migration: Add case about abort job on target host
  libvirt/tests/cfg/migration/abort_precopy_migration/abort_by_domjobabort_on_target.cfg
  libvirt/tests/src/migration/abort_precopy_migration/abort_by_domjobabort_on_target.py
  provider/migration/migration_base.py
Labels: modular_redesign

#4952 numa_topology_with_hugepage: add case numa topology with hugepage
  libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_hugepage.cfg
  libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
  provider/numa/numa_base.py
Labels: depend on

#4976 svirt: Fix incorrect 'status_error' issue
  libvirt/tests/cfg/svirt/shared_storage/svirt_nfs_disk.cfg
Labels: minorfix

#4872 migration: Add case for disk with backingchain
  libvirt/tests/cfg/migration_with_copy_storage/migration_with_backingchain.cfg
  libvirt/tests/src/migration_with_copy_storage/migration_with_backingchain.py
Labels: modular_redesign

#4950 guest_os_booting: add new case for ovmf nvram
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_nvram.cfg
  libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_nvram.py
Labels: modular_redesign

#4982 svirt: Change nfs settings from global to test case specific
  libvirt/tests/cfg/svirt/shared_storage/svirt_nfs_disk.cfg
Labels: minorfix

#4992 migration: Add libvirt version check
  libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_shared_tpm.cfg
  libvirt/tests/src/migration/migration_with_vtpm/migration_with_shared_tpm.py
Labels: minorfix

#5000 memory_snapshot_delete: fix version checking
  libvirt/tests/cfg/snapshot/memory_snapshot_delete.cfg
  libvirt/tests/src/snapshot/memory_snapshot_delete.py
Labels: minorfix

#4999 numa_various_numa_topology_settings: Enable test for aarch64
  libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
Labels: minorfix

#4998 numa_topology_with_numa_distance: Enable test for aarch64
  libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_numa_distance.cfg
Labels: minorfix
