Repository autotest/tp-libvirt, pull requests merged in 2023-07, with the labels that each got.

#5003 memory_binding_setting: fix cgroup v1 checking
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Labels: minorfix

#4995 migration: Fix a parameter error
  provider/migration/migration_base.py
Labels: depend on

#5006 svirt_umask_value: Enable test for aarch64
  libvirt/tests/cfg/svirt/umask_value/svirt_umask_files_accessed_by_qemu.cfg
Labels: minorfix

#5015 timer_management: Remove hpet related cases.
  libvirt/tests/cfg/timer_management.cfg
Labels: minorfix

#5005 numa_memory_spread: Make sure enough memory for guest
  libvirt/tests/src/numa/numa_memory_spread.py
Labels: minorfix

#5013 numa_topology: skip dies related tests on aarch64
  libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_cpu_topology.cfg
Labels: minorfix

#5017 numa: Add version check for discard and emulator tests
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
  libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
  libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
Labels: minorfix

#5014 memory_binding_with_emulator_thread: fix error message
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
Labels: minorfix

#5019 numa_invalid_nodes: Update error message
  libvirt/tests/cfg/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.cfg
Labels: minorfix

#5020 numa_memory_binding_setting: Enable tests for aarch64
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_setting.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Labels: minorfix, arm

#4861 Merge daemon folders
  libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/host_uuid.cfg
  libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/prefix_num.cfg
  libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/processing_controls.cfg
  libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/set_audit_logging.cfg
  libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/unix_sock.cfg
  libvirt/tests/cfg/daemon/conf_file/qemu_conf/auto_dump.cfg
  libvirt/tests/cfg/daemon/conf_file/qemu_conf/clear_emulator_capabilities.cfg
  libvirt/tests/cfg/daemon/conf_file/qemu_conf/seccomp_sandbox.cfg
  libvirt/tests/cfg/daemon/conf_file/qemu_conf/set_process_name.cfg
  libvirt/tests/cfg/daemon/conf_file/qemu_conf/set_virtlogd.cfg
  libvirt/tests/cfg/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.cfg
  libvirt/tests/cfg/daemon/conf_file/sysconfig_libvirtd/libvirtd_config.cfg
  libvirt/tests/cfg/daemon/conf_file/systemd_config/systemd_config.cfg
  libvirt/tests/cfg/daemon/libvirtd/libvirtd.cfg
  libvirt/tests/cfg/daemon/libvirtd/libvirtd_multi_conn.cfg
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/host_uuid.py
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/prefix_num.py
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/processing_controls.py
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/set_audit_logging.py
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/unix_sock.py
  libvirt/tests/src/daemon/conf_file/qemu_conf/auto_dump.py
  libvirt/tests/src/daemon/conf_file/qemu_conf/clear_emulator_capabilities.py
  libvirt/tests/src/daemon/conf_file/qemu_conf/seccomp_sandbox.py
  libvirt/tests/src/daemon/conf_file/qemu_conf/set_process_name.py
  libvirt/tests/src/daemon/conf_file/qemu_conf/set_virtlogd.py
  libvirt/tests/src/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
  libvirt/tests/src/daemon/conf_file/sysconfig_libvirtd/libvirtd_config.py
  libvirt/tests/src/daemon/conf_file/systemd_config/systemd_config.py
  libvirt/tests/src/daemon/libvirtd/libvirtd.py
  libvirt/tests/src/daemon/libvirtd/libvirtd_multi_conn.py
Labels: minorfix

#5023 Fixup:update dmesg check list to be compatible with new version
  libvirt/tests/cfg/memory/hmat.cfg
  libvirt/tests/src/memory/hmat.py
Labels: minorfix

#5030 watchdog:skip model itco for pseries
  libvirt/tests/cfg/virtual_device/watchdog.cfg
Labels: minorfix

#5032 cpu: Remove cases about iothread 'poll-' value validation
  libvirt/tests/cfg/cpu/iothread.cfg
Labels: minorfix

#5026 guest_os_booting_base.py: add firmware_type argument for ovmf guest
  provider/guest_os_booting/guest_os_booting_base.py
Labels: minorfix

#4924 guest_os_booting: add new case for ovmf smm
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_smm.cfg
  libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_smm.py
Labels: depend on, modular_redesign

#5024 virtual_disk: wait for the disk be ready in guest
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#5049 virtual_networks: Increase trafic for comparing iface stat between host and guest
  libvirt/tests/src/virtual_network/iface_stat.py
Labels: minorfix

#5050 sriov: Fixup an issue due to error message change
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_managedsave.cfg
Labels: minorfix

#5047 virtual_disk: Wait for partition to be ready before mkfs
  libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Labels: minorfix

#5057 managed_save: Add version check for xpath_opt
  libvirt/tests/cfg/save_and_restore/save_image_dumpxml.cfg
  libvirt/tests/src/save_and_restore/save_image_dumpxml.py
Labels: minorfix

#4990 chardev: add case for prevent muti console connection
  libvirt/tests/cfg/chardev/virsh_console_operation/prevent_multiple_console.cfg
  libvirt/tests/src/chardev/virsh_console_operation/prevent_multiple_console.py
Labels: depend on, modular_redesign

#5056 memory: disable tests for s390x
  libvirt/tests/cfg/memory/memory_allocation/lifecycle_with_memory_allocation.cfg
  libvirt/tests/cfg/memory/memory_allocation/memory_invalid_value.cfg
Labels: minorfix

#5054 Update for option format -- added
  libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
  libvirt/tests/src/cpu/guestpin.py
  libvirt/tests/src/cpu/powerpc_hmi.py
  libvirt/tests/src/numa/numa_config_with_auto_placement.py
Labels: depend on

#5062 numa: Fix options for `virsh numatune`
  libvirt/tests/src/numa/numa_memory_migrate.py
Labels: minorfix
