Repository autotest/tp-libvirt, pull requests merged in 2023-09, with the labels that each got.

#4941 memory: add case for hugepage nodeset
  libvirt/tests/cfg/memory/memory_backing/hugepage_nodeset.cfg
  libvirt/tests/src/memory/memory_backing/hugepage_nodeset.py
  spell.ignore
Labels: modular_redesign

#5154 virsh.emulatorpin: add alternative error msg for negative test
  libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
Labels: minorfix

#5060 virtual_disks: stabilize tests that check a new disk was added
  libvirt/tests/cfg/virtual_disks/startup_policy.cfg
  libvirt/tests/src/virtual_disks/startup_policy.py
  libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py
  libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Labels: minorfix, depend on

#5148 add case for blockcopy with zero length disk
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_zero_length_disk.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_zero_length_disk.py
Labels: modular_redesign

#5010 guest_os_booting: add new case for seabios rebootTimeout
  libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_rebootimeout.cfg
  libvirt/tests/src/guest_os_booting/seabios_firmware/seabios_rebootimeout.py
Labels: modular_redesign

#5158 libvirt_rng.multiple_rng: run socat on all archs
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#5165 virtio: update virtio pattern to virtio_attributes
  libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
Labels: minorfix

#4946 change_vcpu_pin: add case numa with vcpupin
  libvirt/tests/cfg/numa/guest_numa_topology/change_vcpu_pin.cfg
  libvirt/tests/src/numa/guest_numa_topology/change_vcpu_pin.py
  libvirt/tests/src/virtual_network/connectivity/connectivity_check_network_interface.py
  provider/numa/numa_base.py
Labels: depend on

#5166 Fix agent lifecycle issue
  libvirt/tests/src/guest_agent/agent_lifecycle.py
Labels: minorfix

#5170 virsh_save/restore: improve tear down
  libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
  libvirt/tests/src/virsh_cmd/domain/virsh_save.py
Labels: minorfix

#5167 cpu: fix several tests on s390x
  libvirt/tests/cfg/cpu/vcpu_misc.cfg
  libvirt/tests/cfg/cpu/vm_features.cfg
  libvirt/tests/src/cpu/vcpu_metrics.py
Labels: minorfix

#5156 virsh_event: change mount-point to avoid conflict at teardown
  libvirt/tests/src/event/virsh_event.py
Labels: minorfix

#5169 Improve compatibility by filtering serial device operations
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
Labels: minorfix

#5040 crypto_create_destroy: add checkpoint
  libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
Labels: depend on

#5186 virsh_restore: Fix variable not assignment
  libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
Labels: minorfix

#5175 virsh_domstate: Slow test down to remove brittleness
  libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Labels: minorfix

#5168 startup_policy: fix teardown
  libvirt/tests/src/virtual_disks/startup_policy.py
Labels: minorfix

#5187 incremental_backup: add timeout before doing the backup.
  libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Labels: minorfix

#5201 virtual_disk: Update disk image to enable test on aarch64
  libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
Labels: minorfix

#5209 v2v: fix 8.9 func TC "v2v_options..log_check"
  v2v/tests/cfg/v2v_options.cfg
Labels: minorfix

#5210 graphics: Cleanup env
  libvirt/tests/src/graphics/graphics_functional.py
Labels: minorfix
