Repository autotest/tp-libvirt, pull requests merged in 2023-04, with the labels that each got.

#4829 fix blockcommit low speed
  libvirt/tests/cfg/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.cfg
Labels: minorfix

#4833 Update driver_packed attribute on mem/input/video device
  libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
  libvirt/tests/src/virtual_device/input_devices.py
  libvirt/tests/src/virtual_device/video_devices.py
Labels: depend on

#4856 secret_disk: use EventTracker to wait for detach_device to complete
  libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
Labels: minorfix

#4857 migration: Fix define guest error
  libvirt/tests/src/migration/migrate_with_legacy_guest.py
Labels: depend on

#4832 migration: Remove some redundant params
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Labels: minorfix

#4862 virsh_detach_device_alias: fix watchdog test case
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
Labels: minorfix

#4815 svirt: Add a case about selinux
  libvirt/tests/cfg/svirt/selinux/selinux_seclabel_overall_domain.cfg
  libvirt/tests/src/svirt/selinux/selinux_seclabel_overall_domain.py
Labels: critical_case, modular_redesign
