Repository autotest/tp-libvirt, pull requests merged in 2023-12, with the labels that each got.

#5136 host_numa_info: add case
  libvirt/tests/cfg/numa/host_numa/host_numa_info.cfg
  libvirt/tests/src/numa/host_numa/host_numa_info.py
  spell.ignore
Labels: depend on, request_test_on_arm

#5318 iface_options: use multiline regex for checks
  libvirt/tests/src/virtual_network/iface_options.py
Labels: minorfix

#5234 migration: Add bandwidth limit case
  libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
  libvirt/tests/src/migration_with_copy_storage/migration_bandwidth_limit.py
  provider/migration/migration_base.py
Labels: depend on

#5308 Fix serial.pty.log.file failure on s390x
  libvirt/tests/src/serial/serial_pty_log.py
Labels: minorfix

#5325 numa: Update the attribute for online nodes
  libvirt/tests/src/numa/host_numa/host_numa_info.py
Labels: minorfix

#5293 add case for invalid virtio-mem config
  libvirt/tests/cfg/memory/memory_devices/invalid_virtio_mem_config.cfg
  libvirt/tests/src/memory/memory_devices/invalid_virtio_mem_config.py
  provider/memory/memory_base.py
Labels: depend on, request_test_on_arm

#5237 migration: Add listen address case
  libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_listen_address.cfg
  libvirt/tests/src/migration_with_copy_storage/network_data_transport/tcp.py
Labels: depend on

#5206 add case for period config of memballoon
  libvirt/tests/cfg/memory/memory_balloon/period_config_of_memory_balloon.cfg
  libvirt/tests/src/memory/memory_balloon/period_config_of_memory_balloon.py
Labels: request_test_on_arm

#5263 add case for invalid dimm device config
  libvirt/tests/cfg/memory/memory_devices/invalid_dimm_memory_device_config.cfg
  libvirt/tests/src/memory/memory_devices/invalid_dimm_memory_device_config.py
Labels: modular_redesign, request_test_on_arm

#5338 libvirt_rng: Add alternative expected error
  libvirt/tests/cfg/libvirt_rng.cfg
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#5336 Use 'systemctl list-units' to check daemons' status
  libvirt/tests/src/daemon/check_daemon_after_remove_pkgs.py
Labels: minorfix

#5334 Start virtqemud for the modular daemon mode
  libvirt/tests/src/daemon/conf_file/qemu_conf/set_virtlogd.py
Labels: minorfix

#5347 cpu: Skip host-model for aarch64
  libvirt/tests/cfg/cpu/vcpu_cve.cfg
Labels: minorfix

#5330 lifecycle_time: relax test condition
  libvirt/tests/src/cpu/lifecycle_time.py
Labels: minorfix

#5290 add case for virtio-mem access and discard setting
  libvirt/tests/cfg/memory/memory_devices/virtio_mem_access_and_discard.cfg
  libvirt/tests/src/memory/memory_devices/virtio_mem_access_and_discard.py
Labels: request_test_on_arm

#5353 Unify the name of the vdpa cases
  libvirt/tests/cfg/virtual_network/locked_memory_vdpa/mem_lock_limit_multiple_vdpa_interfaces.cfg
Labels: minorfix

#5226 guest_os_booting: add new case of virtiofs device booting
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_virtiofs_device.cfg
  libvirt/tests/src/guest_os_booting/boot_order/boot_from_virtiofs_device.py
Labels: depend on

#5358 fix memory numa case name
  libvirt/tests/cfg/memory/memory_devices/virtio_mem_auto_placement.cfg
Labels: minorfix

#5352 virtual_disks_multidisks: fix disk discovery
  libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix, depend on

#5351 virtual_disks_transient_disk: fix disk discovery
  libvirt/tests/src/virtual_disks/virtual_disks_transient_disk.py
Labels: depend on

#5323 virtual_disks_multivms: fix disk discovery
  libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Labels: depend on
