Repository autotest/tp-libvirt, pull requests merged in 2023-11, with the labels that each got.

#5245 Add vms = avocado-vt-vm1 vm1 back to scsi_device.cfg
  libvirt/tests/cfg/scsi/scsi_device.cfg
Labels: minorfix

#5212 memory_binding_setting: Add cgroup v1 adaption for cpuset.mems
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Labels: minorfix

#5244 memory_misc:update code according to xml class change
  libvirt/tests/cfg/memory/memory_misc.cfg
Labels: depend on

#5258 virtual_disk: fix positional arguments mismatch in function definition and call
  libvirt/tests/src/scsi/scsi_device.py
Labels: minorfix

#5264 v2v: fix cfg error
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#5124 virsh_pool: add case with rbd pool
  libvirt/tests/cfg/storage/virsh_pool.cfg
  libvirt/tests/deps/cve_2023_3750.sh
  libvirt/tests/src/storage/virsh_pool.py
  provider/virtual_disk/disk_base.py
Labels: depend on

#5102 guest_os_booting: add new modular case for os acpi test
  libvirt/tests/cfg/guest_os_booting/firmware_configuration/os_acpi.cfg
  libvirt/tests/src/guest_os_booting/firmware_configuration/os_acpi.py
Labels: depend on

#5172 Add case to check virt-admin default log_outputs in various conditions
  libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/virt_admin_logging.cfg
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/virt_admin_logging.py
Labels: depend on

#5275 v2v: add a new case for no entry networkname in vmx file
  v2v/tests/cfg/function_test_esx.cfg
Labels: minorfix

#5281 memory_binding_with_emulator_thread: fix cpu model for arm
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
Labels: request_test_on_arm

#5254 iothread: add case with two iothread inactive
  libvirt/tests/cfg/cpu/iothread.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadadd.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreaddel.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadinfo.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadpin.cfg
  libvirt/tests/src/cpu/iothread.py
  libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py
  libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py
Labels: depend on

#5294 Fix typo issues
  libvirt/tests/src/migration/memory_copy_mode/migration_memory_copy_mode.py
  libvirt/tests/src/migration/migrate_options_shared.py
  libvirt/tests/src/sriov/vIOMMU/sriov_iommu_alias.py
  libvirt/tests/src/virtual_interface/hotplug_mem.py
  libvirt/tests/src/virtual_network/locked_memory_vdpa/hotplug_mem_to_vm_with_multiple_vdpa_interfaces.py
  libvirt/tests/src/virtual_network/locked_memory_vdpa/mem_lock_limit_multiple_mixed_interfaces.py
  provider/migration/migration_base.py
Labels: minorfix

#5222 guest os booting: add hotplug case with boot order element
  libvirt/tests/cfg/guest_os_booting/boot_order/hotplug_device_with_boot_order.cfg
  libvirt/tests/src/guest_os_booting/boot_order/hotplug_device_with_boot_order.py
Labels: depend on

#5302 migration: Update error message
  libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_wrong_cert_configuration.cfg
Labels: minorfix

#5300 libvirt_rng: improve regex for virtio device
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#5307 migration: Fix libvirtd service issue
  libvirt/tests/src/migration/migrate_vm.py
Labels: minorfix
