Repository autotest/tp-libvirt, pull requests merged in 2023-05, with the labels that each got.

#4874 guest_numa: fix prefer keyerror
  libvirt/tests/src/numa/guest_numa.py
Labels: minorfix

#4836 misc -> virsh_event: enable crash_panic test for aarch64
  libvirt/tests/cfg/event/virsh_event.cfg
  libvirt/tests/src/event/virsh_event.py
Labels: arm

#4838 add case for lifecycle with memory allocation
  libvirt/tests/cfg/mem/memory_allocation/lifecycle_with_memory_allocation.cfg
  libvirt/tests/src/mem/memory_allocation/lifecycle_with_memory_allocation.py
  spell.ignore
Labels: modular_redesign

#4831 Add copyright and license template into tp-libvirt
  tp-libvirt_review_comment_summary.rst
Labels: minorfix

#4840 tpm_device: add external vtpm tests
  libvirt/tests/cfg/virtual_device/tpm_device.cfg
  libvirt/tests/src/virtual_device/tpm_device.py
Labels: depend on

#4879 Update the tolerance range of calculated dirty page
  libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
Labels: minorfix

#4810 Add case of save with options
  libvirt/tests/cfg/save_and_restore/save_with_options.cfg
  libvirt/tests/src/save_and_restore/save_with_options.py
  provider/save/save_base.py
Labels: depend on

#4850 add case for invalid memory value
  libvirt/tests/cfg/mem/memory_allocation/memory_invalid_value.cfg
  libvirt/tests/src/mem/memory_allocation/memory_invalid_value.py
Labels: modular_redesign

#4875 Update arg list due to modification of utils_net.get_linux_iface_info
  libvirt/tests/src/virtual_network/iface_update.py
  provider/sriov/check_points.py
Labels: depend on

#4890 migration: Remove 'Expected downtime' in domjobinfo output
  libvirt/tests/src/migration/migrate_options_shared.py
Labels: minorfix

#4897 passt:Add libvirt version check
  libvirt/tests/src/virtual_network/passt/passt_function.py
Labels: minorfix

#4864 memory_snapshot_delete: add case for memory snapshot deletion
  libvirt/tests/cfg/snapshot/memory_snapshot_delete.cfg
  libvirt/tests/src/snapshot/memory_snapshot_delete.py
  provider/snapshot/snapshot_base.py
Labels: depend on

#4906 managed_save: Open a new session to get pid of ping
  provider/save/save_base.py
Labels: minorfix

#4913 svirt_dac: Update serial_attrs to enable test for aarch64
  libvirt/tests/cfg/svirt/dac/dac_seclabel_per_device.cfg
Labels: minorfix

#4919 Add the support version for duplicate target cases
  libvirt/tests/cfg/virtual_network/start_vm_with_duplicate_target_dev_name.cfg
  libvirt/tests/src/virtual_network/start_vm_with_duplicate_target_dev_name.py
Labels: minorfix

#4910 passt:replace session funtion cmd_output with cmd
  libvirt/tests/src/virtual_network/passt/passt_function.py
  provider/virtual_network/passt.py
Labels: depend on

#4794 Life cycle of mixed various memory devices
  libvirt/tests/cfg/memory/memory_devices/lifecycle_of_mixed_memory_devices.cfg
  libvirt/tests/src/memory/memory_devices/lifecycle_of_mixed_memory_devices.py
Labels: modular_redesign

#4870 various_numa_topology_settings: add case
  libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
  libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
  provider/numa/numa_base.py
Labels: modular_redesign

#4869 Add case of passt hotplug/unplug
  libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg
  libvirt/tests/src/virtual_network/passt/passt_attach_detach.py
Labels: depend on

#4921 Replace the big file path
  libvirt/tests/src/virtual_network/iface_stat.py
Labels: minorfix
