Repository autotest/tp-libvirt, pull requests merged in 2023-03, with the labels that each got.

#4703 console: Enable detach_device_alias of hostdev pci test for aarch64
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Labels: arm

#4780 cpu/iothread: add error message variant
  libvirt/tests/cfg/cpu/iothread.cfg
Labels: minorfix

#4784 serial_functional: fix missing new parameter
  libvirt/tests/src/serial/serial_functional.py
Labels: minorfix

#4790 guest_numa:raise if catch unexpected error
  libvirt/tests/src/numa/guest_numa.py
Labels: minorfix

#4791 Fixed a misplaced else
  libvirt/tests/src/virsh_cmd/monitor/virsh_dommemstat.py
Labels: minorfix

#4793 virsh_managedsave:Fail test if timeout when waiting for certain vm state
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Labels: minorfix

#4797 backingchain: Fix nbd server is not ready
  provider/virtual_disk/disk_base.py
Labels: minorfix

#4719 sriov: Add a test about smmuv3 iommu device
  libvirt/tests/cfg/sriov/vIOMMU/sriov_iommu_alias.cfg
Labels: minorfix, arm

#4798 virtual_devices/video_devices: disable unsupported cases on s390x
  libvirt/tests/cfg/virtual_device/video_devices.cfg
Labels: minorfix

#4734 libvirtd_conf/unix_sock.py: fix function call error
  libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
Labels: minorfix

#4795 vm_features: add case using features in domcap
  libvirt/tests/cfg/cpu/vm_features.cfg
  libvirt/tests/src/cpu/vm_features.py
Labels: depend on

#4817 migration: Fix issue about migration speed
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#4818 cpu: Fix vm login timeout issue
  libvirt/tests/cfg/cpu/setvcpu.cfg
  libvirt/tests/src/cpu/setvcpu.py
Labels: minorfix

#4819 fix blockcopy not find xml
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_xml_option_to_luks_slice_image.py
Labels: minorfix

#4801 numa: make sure free memory is enough for memhog
  libvirt/tests/src/numa/numa_memory_spread.py
Labels: minorfix

#4812 kernel_panic:Replace exception call type
  libvirt/tests/src/kernel_panic.py
Labels: minorfix, depend on

#4771 backingchain: add case for checking allocation during blockcommit
  libvirt/tests/cfg/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.cfg
  libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
Labels: modular_redesign

#4803 svirt: Add a case about dac
  libvirt/tests/cfg/svirt/dac/dac_seclabel_overall_domain.cfg
  libvirt/tests/src/svirt/dac/dac_seclabel_overall_domain.py
Labels: critical_case, modular_redesign
