Repository autotest/tp-libvirt, pull requests merged in 2023-02, with the labels that each got.

#4731 migration: Update error message
  libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy_unsupported_feature_combinations.cfg
Labels: minorfix

#4702 virtual_interface: Add cases about vdpa interface
  libvirt/tests/cfg/virtual_interface/connectivity_check.cfg
  libvirt/tests/cfg/virtual_interface/locked_memory_check/mem_lock_limit_multiple_vdpa_interfaces.cfg
  libvirt/tests/src/virtual_interface/connectivity_check.py
  libvirt/tests/src/virtual_interface/locked_memory_check/mem_lock_limit_multiple_vdpa_interfaces.py
Labels: depend on

#4716 graphics_functional: Remove remote-viewer checkpoint
  libvirt/tests/cfg/graphics/graphics_functional.cfg
Labels: minorfix

#4712 [MinorFix]Modify the tolerance of the difference
  libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
Labels: minorfix

#4739 virsh_domdirtyrate_calc: no dirty-ring on s390 and aarch64
  libvirt/tests/cfg/virsh_cmd/domain/virsh_domdirtyrate_calc.cfg
Labels: minorfix

#4751 guest_numa: add more memory
  libvirt/tests/cfg/numa/guest_numa.cfg
Labels: minorfix

#4687 backingchain:add case for block operation after lifecycle
  libvirt/tests/cfg/backingchain/lifecycle/block_operation_after_lifecycle.cfg
  libvirt/tests/src/backingchain/lifecycle/block_operation_after_lifecycle.py
  provider/backingchain/blockcommand_base.py
Labels: modular_redesign

#4759 migration: Fix unattended migration error
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Labels: minorfix

#4760 virsh_cpu_compare_xml:Fix error of parsing invalid test xml
  libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare_xml.py
Labels: minorfix

#4761 migration: Fix recover postcopy migration error
  libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Labels: minorfix

#4682 Backingchain: add case of doing block operations repeatedly
  libvirt/tests/cfg/backingchain/repeatability_test/commit_pull_copy_after_snap.cfg
  libvirt/tests/src/backingchain/repeatability_test/commit_pull_copy_after_snap.py
Labels: modular_redesign

#4677 vcpu_sched_core: add case for sched_core
  libvirt/tests/cfg/cpu/vcpu_sched_core.cfg
  libvirt/tests/src/cpu/vcpu_sched_core.py
Labels: depend on

#4755 [guest_resource_control] Add cases to check negative cfs_quota values
  libvirt/tests/cfg/guest_resource_control/control_cgroup.cfg
Labels: depend on

#4767 libvirt_rng:Fix error when calling 'get_devices'
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#4674 backingchain:add case for blockcopy wth different dest xml
  libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_dest_xml.cfg
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_different_dest_xml.py
  provider/virtual_disk/disk_base.py
Labels: depend on, modular_redesign

#4769 Fix input device failures due to element order change
  libvirt/tests/src/virtual_device/input_devices.py
Labels: minorfix

#4763 pcibridge.py: update the method of login guest to fix timeout
  libvirt/tests/src/controller/pcibridge.py
Labels: minorfix
