Repository autotest/tp-libvirt, pull requests merged in 2023-08, with the labels that each got.

#5067 selinux_seclabel_per_device: set correct device for s390x
  libvirt/tests/cfg/svirt/selinux/selinux_seclabel_per_device.cfg
Labels: minorfix

#5068 label_restore_rules: fix image format
  libvirt/tests/src/svirt/label_restore_rules/label_restore_rules_disk_access_modes.py
Labels: minorfix

#5071 dac_seclabel_per_device: fix serial config
  libvirt/tests/cfg/svirt/dac/dac_seclabel_per_device.cfg
Labels: minorfix

#5065 Move actions related to tpm lib's permissions to provider
  libvirt/tests/src/svirt/dac/dac_seclabel_overall_domain.py
  provider/security/security_base.py
Labels: minorfix

#5069 virtual_disks_multivms: fix image format
  libvirt/tests/cfg/virtual_disks/virtual_disks_multivms.cfg
Labels: minorfix

#5070 svirt/umask_value: enable huge pages on s390x
  libvirt/tests/cfg/svirt/umask_value/svirt_umask_files_accessed_by_qemu.cfg
Labels: minorfix

#5081 watchdog: run tco tests only with q35 machine
  libvirt/tests/cfg/virtual_device/watchdog.cfg
Labels: minorfix

#4968 guest_os_booting: add new case for ovmf firmware feature
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.cfg
  libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.py
Labels: modular_redesign

#5084 passt:Replace hardcoded 'eno1' with vm_iface
  provider/virtual_network/passt.py
Labels: minorfix

#4991 guest_os_booting: add new case for seabios loader
  libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_loader.cfg
  libvirt/tests/src/guest_os_booting/seabios_firmware/seabios_loader.py
Labels: modular_redesign

#5079 virsh_detach_device_alias: fix for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Labels: minorfix

#5043 Fix the ovmf smm failure of inconsistency between os xml and smm status
  libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_smm.py
Labels: minorfix

#5088 virsh_nodeinfo: skip on AMD
  libvirt/tests/cfg/virsh_cmd/host/virsh_nodeinfo.cfg
  libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Labels: minorfix

#4963 chardev:add case for chardev release console
  libvirt/tests/cfg/chardev/virsh_console_operation/release_console.cfg
  libvirt/tests/src/chardev/virsh_console_operation/release_console.py
Labels: depend on, modular_redesign

#5091 Fixup:add config for direct type interface to fix ping failure
  libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_direct_interface.cfg
Labels: minorfix

#4970 numa: add case for numa mem binding with offline cpu
  libvirt/tests/cfg/numa/guest_numa_node_tuning/numa_mem_binding_with_offline_cpu.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/numa_mem_binding_with_offline_cpu.py
Labels: modular_redesign

#5076 virtaul_disk: Update regrex for alias_plus_boot_order
  libvirt/tests/src/scsi/scsi_device.py
Labels: minorfix

#5039 auto_memory_nodeset_placement: add case auto mem nodeset and placement
  libvirt/tests/cfg/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.py
  spell.ignore
Labels: depend on

#5110 iface_update.cfg: update error msg
  libvirt/tests/cfg/virtual_network/iface_update.cfg
Labels: minorfix

#5106 migrate_options_shared: Increase low_speed for aarch64
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#5107 numa_topology_with_hugepage: rename hugepage path param
  libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
Labels: minorfix, depend on

#5098 migration: Fix image path error
  provider/migration/base_steps.py
Labels: minorfix

#5109 chardev_pcie: Update controller index for modify_vm_device
  libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Labels: minorfix

#5111 migration: Update migration parameter
  libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls_destination.cfg
  libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls_wrong_cert_configurations.cfg
Labels: minorfix, depend on

#5048 v2v: add TC "Clear error msg when no vpx username"
  v2v/tests/cfg/function_test_esx.cfg
Labels: depend on

#4954 specific_numa_memory_bind_hugepage: add case
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
  libvirt/tests/cfg/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/change_numa_tuning.py
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
  libvirt/tests/src/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.py
  provider/numa/numa_base.py
Labels: depend on

#5075 virtual_network: Add hotplug test for vdpa interface
  libvirt/tests/cfg/virtual_interface/interface_hotplug.cfg
  libvirt/tests/cfg/virtual_network/hotplug/attach_detach_device/hotplug_hotunplug_vdpa_interface.cfg
  libvirt/tests/src/virtual_interface/interface_hotplug.py
  libvirt/tests/src/virtual_network/hotplug/attach_detach_device/hotplug_hotunplug_vdpa_interface.py
  provider/interface/interface_base.py
Labels: depend on

#5038 virtual_network: Add vm lifecycle test for vdpa interface
  libvirt/tests/cfg/virtual_interface/domain_lifecycle.cfg
  libvirt/tests/cfg/virtual_network/lifecycle/lifecycle_vdpa_interface.cfg
  libvirt/tests/src/virtual_network/lifecycle/lifecycle_vdpa_interface.py
Labels: depend on

#4918 memory: add case for mem value unit definition
  libvirt/tests/cfg/memory/memory_allocation/define_value_unit.cfg
  libvirt/tests/src/memory/memory_allocation/define_value_unit.py
  provider/memory/memory_base.py
Labels: modular_redesign

#5120 numa_memory:Remove ppc settings
  libvirt/tests/src/numa/numa_memory.py
Labels: minorfix

#4930 memory: add case for lifecycle with hugepages
  libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg
  libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
Labels: modular_redesign

#5128 numa: Fix small typo
  libvirt/tests/cfg/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.cfg
Labels: minorfix

#4973 numa: add case for auto mem placement with incompatible host nodeset
  libvirt/tests/cfg/numa/numa_node_tuning/auto_mem_placement_with_incompatible_host_nodeset.cfg
  libvirt/tests/src/numa/numa_node_tuning/auto_mem_placement_with_incompatible_host_nodeset.py
Labels: modular_redesign

#5126 updates for poolxml changes
  libvirt/tests/src/virsh_cmd/pool/virsh_pool_auth.py
  libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
  libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py
  libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
  libvirt/tests/src/virtual_disks/startup_policy.py
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: depend on
