Repository autotest/tp-libvirt, pull requests merged in 2023-01, with the labels that each got.

#4681 fix remove existed copy image issue
  libvirt/tests/src/backingchain/blockcopy/blockcopy_with_conventional_chain.py
Labels: minorfix

#4664 backingchain: add case to check mirror xml after restart service
  libvirt/tests/cfg/backingchain/lifecycle_test/check_mirror_with_restart_libvirtd.cfg
  libvirt/tests/src/backingchain/lifecycle_test/check_mirror_with_restart_libvirtd.py
Labels: modular_redesign

#4696 Fix the lock file error
  libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
Labels: minorfix

#4685 Fix test failure expectations when libvirtd is off.
  libvirt/tests/src/virsh_cmd/domain/virsh_vncdisplay.py
Labels: minorfix

#4633 Backingchain: add new case for event checking test
  libvirt/tests/cfg/backingchain/event_checking_test/commit_pull_copy_event.cfg
  libvirt/tests/src/backingchain/event_checking_test/commit_pull_copy_event.py
Labels: modular_redesign

#4690 Revert "numa_memory: Check appropriate error messages for aarch64"
  libvirt/tests/cfg/numa/numa_memory.cfg
Labels: minorfix

#4697 migration: Update error message
  libvirt/tests/cfg/migration/migrate_service_control.cfg
Labels: minorfix

#4673 Backingchain: add new case with different disk attributes
  libvirt/tests/cfg/backingchain/with_disk_attributes_test/commit_pull_with_disk_driver_attributes.cfg
  libvirt/tests/src/backingchain/with_disk_attributes_test/commit_pull_with_disk_driver_attributes.py
Labels: depend on, modular_redesign

#4591 PCIe Controller, pcie-root-port with index <= bus
  libvirt/tests/cfg/controller/pcie_root_port_controller.cfg
  libvirt/tests/src/controller/pcie_root_port_controller.py
Labels: depend on

#4614 Automate case:use NVME type virtual disk
  libvirt/tests/cfg/virtual_disks/virtual_disks_nvme.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_nvme.py
  spell.ignore
Labels: depend on

#4714 v2v: fix HOME env issue when running in CI
  v2v/tests/src/function_test_xen.py
Labels: minorfix

#4715 migrate_mem: Update the memory of numa cells
  libvirt/tests/cfg/migration/migrate_mem.cfg
Labels: minorfix

#4713 passthrough/pci: teard down properly
  libvirt/tests/src/passthrough/pci/ism_pci_passthrough.py
Labels: minorfix

#4692 virsh_destroy: fix destroy error
  libvirt/tests/src/virsh_cmd/domain/virsh_destroy.py
Labels: minorfix
