Repository autotest/tp-libvirt, pull requests merged in 2023-10, with the labels that each got.

#5204 Remove version check of cases of user type interface
  libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_user_interface.cfg
  libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py
Labels: minorfix

#5220 virtio_page_per_vq: add libvirt version
  libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
  libvirt/tests/src/virtio/virtio_page_per_vq.py
Labels: minorfix

#5025 guest_os_booting: add new case for guest bootmenu
  libvirt/tests/cfg/guest_os_booting/boot_menu/bootmenu.cfg
  libvirt/tests/src/guest_os_booting/boot_menu/bootmenu.py
Labels: modular_redesign

#5061 add case for mem pagelock and shared pages cases
  libvirt/tests/cfg/memory/memory_backing/page_locking_and_shared_pages.cfg
  libvirt/tests/src/memory/memory_backing/page_locking_and_shared_pages.py
Labels: depend on, modular_redesign

#5233 virtual_network: Update the regex of sndbuf
  libvirt/tests/src/virtual_network/elements_and_attributes/element_sndbuf.py
Labels: minorfix

#4984 memory: add case for hugepage mount path
  libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg
  libvirt/tests/src/memory/memory_backing/hugepage_mount_path.py
Labels: depend on, modular_redesign

#5074 add case for discard memory content
  libvirt/tests/cfg/memory/memory_backing/discard_memory_content_setting.cfg
  libvirt/tests/src/memory/memory_backing/discard_memory_content_setting.py
Labels: modular_redesign

#5241 memory: Enable test for aarch64
  libvirt/tests/cfg/memory/memory_backing/memory_access_mode.cfg
Labels: minorfix
