Repository autotest/tp-libvirt, pull requests merged in 2024-01, with the labels that each got.

#5248 guest_os_booting: add new case of smbios feature
  libvirt/tests/cfg/guest_os_booting/firmware_configuration/smbios_mode.cfg
  libvirt/tests/src/guest_os_booting/firmware_configuration/smbios_mode.py
Labels: depend on

#5374 migration: Fix wrong event
  libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
Labels: minorfix

#5387 cpu: Disable host dmesg checks
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_compare.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_stats.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
  libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpuinfo.cfg
Labels: minorfix

#5406 fix blockcopy too fast to test
  libvirt/tests/cfg/backingchain/blockjob/blockjob_pivot_after_irregular_operations.cfg
Labels: minorfix

#5407 libvirtd_conf: improve test error
  libvirt/tests/src/daemon/conf_file/libvirtd_conf/set_audit_logging.py
Labels: minorfix

#5415 crypto_nodedev: improve reliability
  libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
Labels: minorfix

#5409 Fix virsh dump memory-only format kdump-* failure
  libvirt/tests/src/virsh_cmd/domain/virsh_dump.py
Labels: minorfix

#5417 Skip the ipv6 default route check
  provider/virtual_network/passt.py
Labels: minorfix

#5284 auto_memory_placement_numad_fail: add case
  libvirt/tests/cfg/numa/guest_numa_node_tuning/auto_memory_placement_numad_fail.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_placement_numad_fail.py
  provider/numa/numa_base.py
Labels: request_test_on_arm

#5426 memory: disable tests on s390x
  libvirt/tests/cfg/memory/memory_allocation/lifecycle_with_memory_allocation.cfg
  libvirt/tests/cfg/memory/memory_balloon/guest_without_mem_balloon.cfg
  libvirt/tests/cfg/memory/memory_balloon/period_config_of_memory_balloon.cfg
Labels: minorfix

#5421 blkdeviotune: improve test log
  libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
Labels: minorfix
