Repository autotest/tp-libvirt, pull requests merged in 2024-05, with the labels that each got.

#5606 guest_os_booting: Fix a hardcode arch type issue
  libvirt/tests/cfg/guest_os_booting/os_configuration/without_default_os_attributes.cfg
  libvirt/tests/src/guest_os_booting/os_configuration/without_default_os_attributes.py
Labels: minorfix

#5569 guest_kernel_debugging: aarch64 supports panic since libvirt-9.1.0
  libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg
  libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Labels: minorfix

#5607 virtual_disks: Fix vhostvdpa_disk nodedev xml issue
  libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
Labels: minorfix

#5610 virtual_disks_iothreads_queue: fix version checking
  libvirt/tests/src/virtual_disks/virtual_disks_iothreads_queue.py
Labels: minorfix

#5615 migration: Fix xml error
  libvirt/tests/cfg/migration/migrate_mem.cfg
Labels: minorfix

#5616 numa: replace parse_numa_nodeset_to_str() to convert_all_nodes_to_string()
  libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.py
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
  libvirt/tests/src/numa/numa_memory.py
  libvirt/tests/src/numa/numa_memory_migrate.py
  libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
Labels: minorfix, depend on

#5627 Fixup:SoftwareManager not found
  libvirt/tests/src/libvirt_package.py
  libvirt/tests/src/libvirtd_start.py
  libvirt/tests/src/save_and_restore/restore_from_local_file.py
  libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
  libvirt/tests/src/virt_cmd/virt_top.py
  v2v/tests/src/install.py
Labels: minorfix

#5571 guest_os_booting: Correct the supported arch types
  libvirt/tests/cfg/guest_os_booting/boot_menu/bootmenu.cfg
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_disk_device.cfg
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_dev.cfg
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_order.cfg
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.cfg
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.cfg
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_nvram.cfg
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_seclabel_in_nvram.cfg
  libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_loader.cfg
  libvirt/tests/cfg/guest_os_booting/useserial/useserial.cfg
Labels: request_test_on_arm

#5631 numa: remove 'kernelpagesize_kB' parameter
  libvirt/tests/cfg/numa/guest_numa_node_tuning/change_numa_tuning.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/change_numa_tuning.py
Labels: minorfix

#5637 Fix pkg dmidecode missing issue in guest image
  libvirt/tests/src/memory/virsh_setmem.py
Labels: minorfix

#5478 Automate discard_granularity disk attribute cases
  libvirt/tests/cfg/virtual_disks/virtual_disks_discard_granularity.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_discard_granularity.py
Labels: high_case

#5646 guest_os_booting: Skip unsupported cases for aarch64
  libvirt/tests/cfg/guest_os_booting/firmware_configuration/os_acpi.cfg
  libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg
Labels: minorfix

#5640 numa: use dynamic expected value for different architectures
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Labels: minorfix

#5622 add case for dimm memory hotplug
  libvirt/tests/cfg/memory/memory_devices/dimm_memory_hotplug.cfg
  libvirt/tests/src/memory/memory_devices/dimm_memory_hotplug.py
  provider/memory/memory_base.py
Labels: request_test_on_arm

#5590 filesystem_device: test usage for unprivileged users
  libvirt/tests/cfg/virtual_device/filesystem_device_unprivileged.cfg
  libvirt/tests/src/virsh_cmd/host/virsh_sysinfo.py
  libvirt/tests/src/virtual_device/filesystem_device_unprivileged.py
  spell.ignore
Labels: depend on
