Repository autotest/tp-libvirt, pull requests merged in 2024-04, with the labels that each got.

#5553 snapshot case enhancement
  libvirt/tests/src/snapshot/revert_memory_only_snap.py
Labels: minorfix

#5536 Debug cdrom event not found issue
  libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
Labels: minorfix

#5502 add case for revert snap for guest with genid
  libvirt/tests/cfg/snapshot/revert_snap_for_guest_with_genid.cfg
  libvirt/tests/src/snapshot/revert_snap_for_guest_with_genid.py
Labels: depend on

#5548 misc_virtual_devices: fix "No more available PCI slots" error
  libvirt/tests/src/virtual_device/input_devices_plug_unplug.py
Labels: minorfix

#5561 fix snapshot case the libvirt version issue
  libvirt/tests/src/snapshot/revert_memory_only_snap.py
  libvirt/tests/src/snapshot/revert_snap_based_on_state.py
  libvirt/tests/src/snapshot/revert_snap_for_guest_with_genid.py
Labels: minorfix

#5559 virtual_network: Add a case of link state
  libvirt/tests/cfg/virtual_network/link_state/link_state_model_type.cfg
  libvirt/tests/src/virtual_network/link_state/link_state_model_type.py
Labels: depend on

#5386 migration: Add case about query domain job info
  libvirt/tests/cfg/migration/async_job/migration_domjobinfo.cfg
  libvirt/tests/cfg/migration_with_copy_storage/async_job/query_domain_job_info.cfg
  libvirt/tests/src/migration/async_job/migration_domjobinfo.py
  libvirt/tests/src/migration_with_copy_storage/async_job/query_domain_job_info.py
  provider/migration/migration_base.py
Labels: depend on

#5570 virtual_disks: Add 2 cases of vhostvdpa_block
  libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_vhostvdpa_backend_disk.cfg
  libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_vhostvdpa_backend_disk.py
  spell.ignore
Labels: depend on

#5578 Fixup the name typo
  libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_vhostvdpa_backend_disk.cfg
Labels: minorfix

#5586 virtual_network: Extend event_timeout for arm
  libvirt/tests/src/virtual_network/hotplug/attach_detach_interface/attach_interface_with_model.py
Labels: minorfix

#5575 virtual_disk: fix snapshot issue for ovmf guest
  libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Labels: minorfix

#5311 add case for virtio-mem with memory backing type
  libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_backing_type.cfg
  libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_backing_type.py
  provider/memory/memory_base.py
Labels: request_test_on_arm

#5283 add case for changing requested size value of virtio-mem
  libvirt/tests/cfg/memory/memory_devices/change_virtio_mem_request_size.cfg
  libvirt/tests/src/memory/memory_devices/change_virtio_mem_request_size.py
  provider/memory/memory_base.py
Labels: request_test_on_arm

#5530 virtual_disks_driver_iothreads: add case
  libvirt/tests/cfg/virtual_disks/virtual_disks_iothreads_queue.cfg
  libvirt/tests/src/virtual_disks/virtual_disks_iothreads_queue.py
Labels: depend on

#5573 Adaption for rhel8 aarch64
  libvirt/tests/cfg/event/virsh_event.cfg
Labels: minorfix
