Repository autotest/tp-libvirt, pull requests merged in 2024-06, with the labels that each got.

#5659 v2v: fix a minor typo
  provider/v2v_vmcheck_helper.py
Labels: minorfix

#5660 v2v: fix ovirt module import issue
  v2v/tests/src/function_test_esx.py
Labels: minorfix

#5669 migration: Update error message
  libvirt/tests/cfg/migration/migrate_options_shared.cfg
Labels: minorfix

#5676 virsh_emulatorpin: Fix ValueError: invalid mode: 'rU'
  libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
Labels: minorfix

#5682 managedsave_cpu_mode: fix for s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
Labels: minorfix

#5678 virsh_reboot: disable acpi test on s390x
  libvirt/tests/cfg/virsh_cmd/domain/virsh_reboot.cfg
Labels: minorfix

#5651 Fix virsh.set_user_password.normal_test.normal_user.encrypted
  libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
Labels: minorfix

#5674 filesystem_device_unprivileged: fix wrong import
  libvirt/tests/src/virtual_device/filesystem_device_unprivileged.py
Labels: minorfix

#5683 fix not found vmx
  libvirt/tests/src/cpu/vcpu_nested.py
Labels: minorfix

#5662 migration: Update error message
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#5653 Resume the test with ipv6 multipath route
  libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg
  libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
Labels: depend on

#5684 Fix virsh.start.status_error_no.audit_log_search failure in checking …
  libvirt/tests/src/virsh_cmd/domain/virsh_start.py
Labels: minorfix

#5696 net_update: get accurate ip
  libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
Labels: minorfix

#5699 vcpu_misc.cfg, fix for cpu model on maxphysaddr case
  libvirt/tests/cfg/cpu/vcpu_misc.cfg
Labels: minorfix

#5600 host_numa_info: enable 4k test
  libvirt/tests/cfg/numa/host_numa/host_numa_info.cfg
  libvirt/tests/src/numa/host_numa/host_numa_info.py
Labels: request_test_on_arm

#5720 migration: Update error message
  libvirt/tests/cfg/migration/migrate_vm.cfg
Labels: minorfix

#5716 Refactor iommu migration case
  libvirt/tests/src/sriov/vIOMMU/migration_iommu_device.py
Labels: depend on

#5730 vdpa: Fix an issue due to cmd output change
  provider/interface/vdpa_base.py
Labels: minorfix

#5729 Decrease memory balloon period to make memory info collection more frequent
  libvirt/tests/cfg/memory/memory_misc.cfg
Labels: minorfix

#5641 Memory misc add multi huge page size config
  libvirt/tests/cfg/memory/memory_misc.cfg
  libvirt/tests/src/memory/memory_misc.py
Labels: request_test_on_arm

#5735 guest_os_booting: Fix up issues of entering uefi shell
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg
  libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py
Labels: minorfix

#5743 aarch64: fix console connection issue on ARM
  libvirt/tests/cfg/virsh_cmd/domain/virsh_console.cfg
Labels: minorfix
