Repository autotest/tp-libvirt, pull requests merged in 2024-03, with the labels that each got.

#5455 libvirt_rng: revert commit to avoid timeouts
  libvirt/tests/cfg/libvirt_rng.cfg
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#5466 migration: Fix unix socket number issue
  libvirt/tests/src/migration/migrate_over_unix.py
Labels: minorfix

#5472 migration: Update error message
  libvirt/tests/cfg/migration_with_copy_storage/precreate_none_target_disk.cfg
Labels: minorfix

#5458 fix storage case inappropriate message
  libvirt/tests/src/storage/virsh_pool_autostart.py
Labels: minorfix

#5452 attach_detach_disk: fix disk discovery
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Labels: minorfix

#5486 Support pvpanic model panic device on aarch64
  libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Labels: minorfix, arm

#5475 aarch64_cpu_sve: fix issues
  libvirt/tests/src/cpu/aarch64_cpu_sve.py
Labels: arm

#5494 libvirt_rng: fix variable 'output' referenced before assignment
  libvirt/tests/src/libvirt_rng.py
Labels: minorfix

#5326 numa: Fix parsing of more than two consecutive numa nodes
  libvirt/tests/src/numa/guest_numa_node_tuning/host_guest_mixed_memory_binding.py
Labels: minorfix, depend on

#5493 virtual_disk/transient_disk: fix disk discovery for VM1
  libvirt/tests/src/virtual_disks/virtual_disks_transient_disk.py
Labels: minorfix

#5489 Change cpu mode to host-passthrough for aarch64
  libvirt/tests/cfg/memory/hmat.cfg
Labels: minorfix

#5500 cpu_xml: fix negative case with missing feature
  libvirt/tests/deps/negative_domcapabilities_s390x.xml
Labels: minorfix

#5481 Enable sriov tests on arm
  libvirt/tests/cfg/sriov/capabilities/sriov_capabilities_iommu_support.cfg
  libvirt/tests/cfg/sriov/network/sriov_check_net_info_by_network_lifecycle_cmds.cfg
  libvirt/tests/cfg/sriov/network/sriov_define_or_start_network_with_pf_addr.cfg
  libvirt/tests/cfg/sriov/nodedev/sriov_nodedev_non_driver.cfg
  libvirt/tests/cfg/sriov/nodedev/sriov_nodedev_reattach_detach.cfg
  libvirt/tests/cfg/sriov/nodedev/sriov_reattach_detach_nodedev_in_use.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_special_situations.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_with_flags.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_with_unsupported_settings.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_check_connections.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_from_network.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_special_situations.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_with_flags.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_interface_to_vm_with_vf.cfg
  libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_released_hostdev.cfg
  libvirt/tests/cfg/sriov/scalability/sriov_scalability_max_vf.cfg
  libvirt/tests/cfg/sriov/update_device/sriov_update_device.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_exclusive_check_offline_domain.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_exclusive_check_running_domain.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_iommu_at_dt_hostdev.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_managedsave.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_reboot.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_suspend_resume.cfg
  libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_unmanaged.cfg
  libvirt/tests/src/sriov/capabilities/sriov_capabilities_iommu_support.py
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device.py
  libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.py
  provider/sriov/check_points.py
  provider/sriov/sriov_base.py
Labels: arm

#5364 migration: Add case about disks-uri
  libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_disks_uri.cfg
Labels: depend on

#5503 Fix attach-detach disk failure
  libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
Labels: minorfix

#5470 Increase current memory to avoid guest boot failure for short of memory
  libvirt/tests/cfg/libvirt_mem.cfg
  libvirt/tests/cfg/memory/memory_misc.cfg
Labels: minorfix

#5507 virsh_snapshot_disk: log vm state
  libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Labels: minorfix

#5519 Serial: Add a case for testing system-serial on aarch64
  libvirt/tests/cfg/serial/serial_functional.cfg
Labels: minorfix

#5471 lifecycle_for_hugepage: update for arm hugepage
  libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg
  libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
  libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
  provider/numa/numa_base.py
Labels: depend on, arm, request_test_on_arm

#5512 Change huge page assignment automatically to adapt for aarch64.
  libvirt/tests/cfg/memory/memory_devices/lifecycle_of_mixed_memory_devices.cfg
  libvirt/tests/src/memory/memory_devices/lifecycle_of_mixed_memory_devices.py
Labels: request_test_on_arm

#5437 numa: Enable test for ARM 16G hugepage memory
  libvirt/tests/cfg/numa/host_numa/host_numa_info.cfg
  libvirt/tests/src/numa/host_numa/host_numa_info.py
Labels: minorfix, request_test_on_arm

#5531 Increase current memory size to avoid guest crash during bootup
  libvirt/tests/cfg/libvirt_mem.cfg
Labels: minorfix

#5524 boot_from_usb_device: correct file path
  libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg
Labels: minorfix

#5525 migartion: Add libvirt version check for domjobabort
  libvirt/tests/cfg/migration/abort_precopy_migration/abort_by_domjobabort_on_target.cfg
  libvirt/tests/src/migration/abort_precopy_migration/abort_by_domjobabort_on_target.py
Labels: minorfix

#5533 virtual_network/coalesce: normalize ethtool output
  provider/virtual_network/network_base.py
Labels: minorfix

#5442 Check the cpu topology from virsh capabilities is the subset of result from system
  libvirt/tests/src/numa/host_numa/host_numa_info.py
Labels: minorfix

#5526 Change content comparison to subset
  libvirt/tests/src/numa/numa_capabilities.py
Labels: minorfix

#5482 fix multiple numa hugepage cases on arm
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_setting.cfg
  libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
  libvirt/tests/cfg/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.cfg
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
  libvirt/tests/src/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.py
  provider/numa/numa_base.py
Labels: arm

#5366 migration: Add case about migrateuri and disks-port
  libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_migrateuri_and_disks_port.cfg
  libvirt/tests/src/migration_with_copy_storage/network_data_transport/tcp_migrateuri_and_disks_port.py
Labels: depend on

#5549 memory_binding_setting: fix kernelpagesize
  libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Labels: minorfix

#5522 storage_ceph: update the quotes of ceph variant from '' to "" to match the jobs.yaml
  libvirt/tests/cfg/storage/virsh_pool.cfg
Labels: minorfix

#5545 Stop guest start before case execution
  libvirt/tests/cfg/virsh_cmd/domain/virsh_memtune.cfg
  libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py
Labels: minorfix
