Repository autotest/tp-libvirt, pull requests merged in 2025-06, with the labels that each got.

#6346 migration_with_vtpm_state_on_block_dev: fix syntax error
  libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.py
Labels: minorfix

#6350 migrate_mem: restore configuration for s390x
  libvirt/tests/cfg/migration/migrate_mem.cfg
Labels: minorfix

#6355 migration: Fix decode failure
  libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.cfg
  libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.py
Labels: minorfix

#6352 virtual_disks: fix sgio issue with multipath disk
  libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
Labels: minorfix

#6348 SRIOV: fix an expected error message issue
  libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_aw_bits.cfg
Labels: minorfix

#6361 migration: Fix the SSH connection issue
  libvirt/tests/cfg/migration_with_copy_storage/async_job/query_domain_job_info.cfg
Labels: minorfix

#6249 automate VIRT-303225 - [vIOMMU] virsh reset when booting guest for 10+ times
  libvirt/tests/cfg/sriov/vIOMMU/iommu_repeated_reset.cfg
  libvirt/tests/src/sriov/vIOMMU/iommu_repeated_reset.py
Labels: depend on

#6366 migration: Update error message
  libvirt/tests/cfg/migration/destructive_operations_around_live_migration/kill_qemu_during_performphase.cfg
Labels: minorfix

#6328 passt: Replace the test file dir '/' with '/var/tmp'
  libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg
Labels: minorfix

#6305 passthrough/ccw: update disk selection
  libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough.cfg
  libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough_read_write.cfg
  libvirt/tests/cfg/virtual_disks/virtual_disks_dasd.cfg
  libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py
  libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough_read_write.py
  libvirt/tests/src/virtual_disks/virtual_disks_dasd.py
  provider/vfio/ccw.py
  provider/vfio/mdev_handlers.py
  virttools/tests/cfg/virt_install/blk_installation.cfg
  virttools/tests/cfg/virt_install/hostdev_mdev.cfg
  virttools/tests/cfg/virt_install/vfio_installation.cfg
  virttools/tests/src/virt_install/blk_installation.py
  virttools/tests/src/virt_install/hostdev_mdev.py
  virttools/tests/src/virt_install/vfio_installation.py
Labels: depend on

#6369 update_device: Replace str_out() with __str__()
  libvirt/tests/src/virtual_network/update_device/update_iface_type_live.py
Labels: minorfix

#6386 nvdimm: Add libvirt version check for snapshot revert
  libvirt/tests/src/memory/nvdimm.py
Labels: minorfix

#6356 migration: Sleep to wait bandwidth change
  libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
Labels: minorfix

#6394 migration: Update loop time
  libvirt/tests/cfg/migration/async_ops/query_info_during_migration.cfg
  provider/migration/migration_base.py
Labels: minorfix

#6398 migration: Update error message
  libvirt/tests/cfg/migration/destructive_operations_around_live_migration/kill_qemu_during_performphase.cfg
Labels: minorfix

#6416 Update parameter name in batch
  libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg
  libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_backing_type.cfg
  libvirt/tests/src/memory/memory_backing/hugepage_mount_path.py
  libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_backing_type.py
Labels: minorfix, depend on
