Repository autotest/tp-libvirt, pull requests merged in 2025-05, with the labels that each got.

#6306 sriov: Extend event wait time
  libvirt/tests/src/sriov/locked_memory_check/sriov_with_hotplug_memory.py
Labels: minorfix

#6270 GPU: Add cases for aarch64
  libvirt/tests/cfg/gpu/hotplug_gpu.cfg
  libvirt/tests/cfg/gpu/lifecycle_vm_with_gpu.cfg
  libvirt/tests/cfg/gpu/start_vm_with_gpu.cfg
  libvirt/tests/cfg/gpu/start_vm_with_gpu_managed_disabled.cfg
  libvirt/tests/cfg/gpu/vm_cuda_sanity.cfg
  libvirt/tests/cfg/gpu/vm_mig_sanity.cfg
  libvirt/tests/cfg/gpu/vm_nvidia_gpu_driver.cfg
  libvirt/tests/src/gpu/hotplug_gpu.py
  libvirt/tests/src/gpu/lifecycle_vm_with_gpu.py
  libvirt/tests/src/gpu/start_vm_with_gpu.py
  libvirt/tests/src/gpu/start_vm_with_gpu_managed_disabled.py
  libvirt/tests/src/gpu/vm_cuda_sanity.py
  libvirt/tests/src/gpu/vm_mig_sanity.py
  libvirt/tests/src/gpu/vm_nvidia_gpu_driver.py
  provider/gpu/__init__.py
  provider/gpu/gpu_base.py
Labels: arm

#6307 migration: Update migration_bandwidth_limit case
  libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
Labels: minorfix

#6300 virtiofs: fix negative scenarios
  libvirt/tests/src/virtiofs/virtiofs.py
Labels: minorfix

#6326 Remove 2 checkpoints for passt
  libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg
  libvirt/tests/src/virtual_network/passt/passt_attach_detach.py
  libvirt/tests/src/virtual_network/passt/passt_function.py
  libvirt/tests/src/virtual_network/passt/passt_reconnect.py
Labels: minorfix

#6330 passt: support multiple default routes
  libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg
  libvirt/tests/cfg/virtual_network/passt/passt_function.cfg
  libvirt/tests/cfg/virtual_network/passt/passt_lifecycle.cfg
  libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg
  libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg
  libvirt/tests/src/virtual_network/passt/passt_attach_detach.py
  libvirt/tests/src/virtual_network/passt/passt_function.py
  libvirt/tests/src/virtual_network/passt/passt_lifecycle.py
  libvirt/tests/src/virtual_network/passt/passt_reconnect.py
  libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
  provider/virtual_network/passt.py
Labels: depend on

#6338 Remove systemd-run when run virtiofsd process
  libvirt/tests/src/virtiofs/virtiofs.py
Labels: minorfix

#6341 nvdimm: disable test on s390x
  libvirt/tests/cfg/memory/memory_devices/nvdimm_memory_turn_to_dram.cfg
Labels: minorfix
